// src/client/components/shared/NotFound.tsx
import { Link } from "react-router";
import { ArrowLeft } from "lucide-react";
import { useTranslation } from "@/client/providers";
import { PageContainer } from "@/client/components/layout";

/** 404 page with a link back to the home route. */
export function NotFound() {
  const { t } = useTranslation();
  return (
    <PageContainer>
      <div className="flex flex-col items-center justify-center py-20">
        <div className="text-5xl font-semibold text-text-tertiary mb-4">404</div>
        <h1 className="text-xl font-semibold text-text-primary">{t("notFoundTitle")}</h1>
        <p className="mt-2 text-sm text-text-secondary">{t("notFound")}</p>
        <Link
          to="/"
          className="mt-6 inline-flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium text-accent rounded-md hover:bg-accent-light transition-colors"
        >
          <ArrowLeft size={14} />
          {t("backToHome")}
        </Link>
      </div>
    </PageContainer>
  );
}

// src/client/components/feedback/not-found.vue
<script setup lang="ts">
import { ArrowLeft } from "@lucide/vue";
import { cn } from "@/client/utils/cn";
import { useTranslation } from "@/client/i18n";
import { buttonVariants } from "@/client/components/ui/button-variants";
import PageContainer from "@/client/components/layout/page-container.vue";
import SafeLink from "@/client/components/safe-link.vue";

const { t } = useTranslation();
</script>

<template>
  <PageContainer>
    <div class="flex flex-col items-center justify-center gap-4 py-24 text-center">
      <div class="border border-border bg-bg-secondary px-4 py-2 text-4xl sm:text-5xl font-semibold tabular-nums text-text-tertiary">
        404
      </div>
      <h1 class="ui-section-title">{{ t("notFoundTitle") }}</h1>
      <p class="ui-body-secondary max-w-md text-balance">{{ t("notFound") }}</p>
      <SafeLink href="/" :class="cn('mt-2', buttonVariants({ variant: 'primary', size: 'md' }))">
        <ArrowLeft :size="14" />
        {{ t("backToHome") }}
      </SafeLink>
    </div>
  </PageContainer>
</template>
