// src/client/features/status/status-events.vue
<script setup lang="ts">
import { computed } from "vue";
import type { StatusEvent } from "@/shared/types";
import { cn } from "@/client/utils/cn";
import { formatRelativeTime } from "@/client/utils/format";
import { sourceLabel } from "@/shared/config";
import { useTranslation } from "@/client/i18n";
import Dot from "@/client/components/ui/dot.vue";
import EmptyState from "@/client/components/feedback/empty-state.vue";
import { eventDurationLabel, resolveEventStyle } from "@/client/utils/status-events";
import { ROW_PADDING } from "@/client/config/layout";

const props = withDefaults(
  defineProps<{
    events: StatusEvent[];
    emptyMessage: string;
    sourceId?: string;
    limit?: number;
    showSource?: boolean;
    showTime?: boolean;
  }>(),
  { showSource: false, showTime: false },
);

const { t, lang } = useTranslation();

const visible = computed(() => {
  const filtered = props.sourceId ? props.events.filter((event) => event.id === props.sourceId) : props.events;
  return props.limit == null ? filtered : filtered.slice(0, props.limit);
});

function detailOf(event: StatusEvent): string | null {
  return event.type === "up" ? null : (event.detail ?? null);
}

const rows = computed(() =>
  visible.value.map((event) => ({
    event,
    style: resolveEventStyle(event.type),
    detail: detailOf(event),
  })),
);
</script>

<template>
  <EmptyState v-if="visible.length === 0" compact :message="emptyMessage" />
  <div v-else class="ui-card divide-y divide-border">
    <div
      v-for="row in rows"
      :key="`${row.event.id}-${row.event.at}-${row.event.type}`"
      :class="cn('flex items-start justify-between gap-3', ROW_PADDING)"
    >
      <div class="flex items-start gap-2 min-w-0">
        <Dot size="sm" :color="row.style.color" class="mt-1.5" />
        <div class="min-w-0">
          <div class="text-sm">
            <span :class="cn('font-medium', row.style.text)">{{ t(row.style.labelKey) }}</span>
            <template v-if="showSource">
              <span class="text-text-secondary mx-1.5">·</span>
              <span class="text-text-secondary">{{ sourceLabel(row.event.id, t) }}</span>
            </template>
          </div>
          <p
            v-if="row.detail"
            class="ui-caption text-text-secondary mt-0.5 line-clamp-2 break-words"
            :title="row.detail ?? undefined"
          >
            {{ row.detail }}
          </p>
        </div>
      </div>
      <div class="flex items-center gap-2 shrink-0 text-xs text-text-secondary">
        <span v-if="row.event.type !== 'up'" class="font-mono">{{ eventDurationLabel(t, row.event.durationMin) }}</span>
        <span v-if="showTime">{{ formatRelativeTime(row.event.at, t, lang) }}</span>
      </div>
    </div>
  </div>
</template>

// src/client/components/status-events.tsx
"use client";
import { memo } from "react";
import { useTranslation } from "@/client/providers";
import type { StatusEvent } from "@/shared/types";
import { cn } from "@/client/utils/cn";
import { formatRelativeTime } from "@/client/utils/format";
import { SOURCE_LABELS } from "@/shared/config";
import { Dot } from "@/client/components/ui/primitives";
import { EmptyState } from "@/client/components/feedback";

export const EVENT_STYLES = {
  down: { color: "var(--destructive)", text: "text-destructive", labelKey: "eventDown" },
  degraded: { color: "var(--warning)", text: "text-warning", labelKey: "eventDegraded" },
  up: { color: "var(--success)", text: "text-success", labelKey: "eventUp" },
} as const;

export const StatusEventRow = memo(function StatusEventRow({
  event,
  showSource = false,
  showTime = false,
}: {
  event: StatusEvent;
  showSource?: boolean;
  showTime?: boolean;
}) {
  const { t, lang } = useTranslation();
  const style = EVENT_STYLES[event.type];
  const labelKey = Object.hasOwn(SOURCE_LABELS, event.id)
    ? (SOURCE_LABELS as Record<string, (typeof SOURCE_LABELS)[keyof typeof SOURCE_LABELS]>)[event.id]
    : undefined;
  const sourceLabel = labelKey ? t(labelKey) : event.id;
  return (
    <div className="flex items-center justify-between gap-3 px-4 py-3">
      <div className="flex items-center gap-2 min-w-0">
        <Dot size="sm" color={style.color} />
        <span className="text-sm">
          <span className={cn("font-medium", style.text)}>{t(style.labelKey)}</span>
          {showSource && (
            <>
              <span className="text-text-secondary mx-1.5">·</span>
              <span className="text-text-secondary">{sourceLabel}</span>
            </>
          )}
        </span>
      </div>
      <div className="flex items-center gap-2 shrink-0 text-xs text-text-secondary">
        {event.type !== "up" && (
          <span className="font-mono">
            {event.durationMin == null ? t("eventOngoing") : t("eventDurationMin", { value: event.durationMin })}
          </span>
        )}
        {showTime && <span>{formatRelativeTime(event.at, t, lang)}</span>}
      </div>
    </div>
  );
});

export const StatusEventList = memo(function StatusEventList({
  events,
  emptyMessage,
  showSource = false,
  showTime = false,
}: {
  events: StatusEvent[];
  emptyMessage: string;
  showSource?: boolean;
  showTime?: boolean;
}) {
  if (events.length === 0) {
    return <EmptyState compact message={emptyMessage} />;
  }
  return (
    <div className="ui-card divide-y divide-border">
      {events.map((event, idx) => (
        <StatusEventRow
          key={`${event.id}-${event.at}-${event.type}-${idx}`}
          event={event}
          showSource={showSource}
          showTime={showTime}
        />
      ))}
    </div>
  );
});
