// src/client/search/search-input.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { Loader2 } from "@lucide/vue";
import { useRouter } from "vue-router";
import { cn } from "@/client/utils/cn";
import { useTranslation } from "@/client/i18n";
import { useRouteSearchTerm } from "@/client/stores";
import { MIN_QUERY, useSearchAllRankings } from "@/client/search/use-search";
import Combobox from "@/client/search/combobox.vue";
import { useCombobox } from "@/client/search/use-combobox";

const props = defineProps<{ class?: string }>();

const { t } = useTranslation();
const router = useRouter();
const isOpen = ref(false);
const isFocused = ref(false);

const { term: searchTerm, setTerm: setSearchTerm } = useRouteSearchTerm();

const { results, isPending, isError } = useSearchAllRankings(searchTerm, {
  suspended: computed(() => !isOpen.value),
  warm: isFocused,
});

const combobox = useCombobox({
  initialValue: searchTerm.value,
  minQuery: MIN_QUERY,
  itemCount: computed(() => results.value.length),
  isOpen,
  isFocused,
  onSelect: (index) => {
    const result = results.value[index];
    if (result) void router.push(result.link);
  },
});

const { listboxId, activeIndex, inputValue, debounced, onHover, onSelectIndex } = combobox;

watch([debounced, searchTerm], () => {
  if (debounced.value !== searchTerm.value) setSearchTerm(debounced.value);
});

const pending = computed(() => isPending.value || inputValue.value !== searchTerm.value);
</script>

<template>
  <Combobox
    :controller="combobox"
    :class="props.class"
    :status="pending ? undefined : t('searchResultsCount', { count: results.length })"
  >
    <div
      v-if="pending && results.length === 0"
      class="flex items-center justify-center gap-2 p-4 text-sm text-text-secondary"
    >
      <Loader2 class="size-4 animate-spin" aria-hidden="true" />
      {{ t("searching") }}
    </div>
    <div v-else-if="isError && results.length === 0" class="p-4 text-sm text-text-secondary" role="alert">
      {{ t("searchFailed") }}
    </div>
    <div v-else-if="results.length === 0" class="p-4 text-sm text-text-secondary" role="status">
      {{ t("noResults") }}
    </div>
    <template v-else>
      <div
        v-for="(result, index) in results"
        :id="`${listboxId}-option-${index}`"
        :key="`${result.source}-${result.id}`"
        role="option"
        :aria-selected="activeIndex === index"
        :class="
          cn(
            'w-full text-left p-2.5 cursor-pointer transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30',
            activeIndex === index ? 'bg-hover' : 'hoverable:hover:bg-hover',
          )
        "
        @mouseenter="onHover(index)"
        @mousedown.prevent
        @click="onSelectIndex(index)"
      >
        <span class="flex items-center justify-between gap-2">
          <span class="text-sm font-medium text-text-primary truncate">{{ result.name }}</span>
          <span
            v-if="typeof result.score === 'number' && Number.isFinite(result.score)"
            class="text-xs text-text-secondary ml-2 shrink-0 font-mono"
          >
            {{ result.score.toFixed(1) }}
          </span>
        </span>
        <span class="flex items-center gap-2 mt-1">
          <span class="text-xs text-text-secondary">{{ t(result.source) }}</span>
          <span v-if="result.provider" class="text-xs text-text-tertiary">{{ result.provider }}</span>
        </span>
      </div>
    </template>
  </Combobox>
</template>

// src/client/search/search-input.tsx
import { useEffect, useState } from "react";
import { Loader2 } from "lucide-react";
import { cn } from "@/client/utils/cn";
import { useRouter } from "@/client/router";
import { useTranslation } from "@/client/providers";
import { useRouteSearchTerm } from "@/client/stores";
import type { SearchResult } from "@/client/search/types";
import { useSearchAllRankings, MIN_QUERY } from "@/client/search/use-search";
import { Combobox, useCombobox } from "@/client/search/combobox";

export function SearchInput({ className }: { className?: string }) {
  const { t } = useTranslation();
  const router = useRouter();
  const [isOpen, setIsOpen] = useState(false);
  const [isFocused, setIsFocused] = useState(false);

  const { term: searchTerm, setTerm: setSearchTerm } = useRouteSearchTerm();

  const { results, isPending, isError } = useSearchAllRankings(searchTerm, { suspended: !isOpen, warm: isFocused });

  const combobox = useCombobox({
    initialValue: searchTerm,
    minQuery: MIN_QUERY,
    itemCount: results.length,
    isOpen,
    setIsOpen,
    setIsFocused,
    onSelect: (index) => {
      const result = results[index];
      if (result) router.push(result.link);
    },
  });

  useEffect(() => {
    if (combobox.debounced !== searchTerm) setSearchTerm(combobox.debounced);
  }, [combobox.debounced, searchTerm, setSearchTerm]);

  const pending = isPending || combobox.inputValue !== searchTerm;

  return (
    <Combobox
      controller={combobox}
      className={className}
      status={pending ? null : t("searchResultsCount", { count: results.length })}
    >
      <SearchDropdown
        listboxId={combobox.listboxId}
        results={results}
        isPending={pending}
        isError={isError}
        activeIndex={combobox.activeIndex}
        onHover={combobox.onHover}
        onSelect={combobox.onSelectIndex}
      />
    </Combobox>
  );
}

function SearchDropdown({
  listboxId,
  results,
  isPending,
  isError,
  activeIndex,
  onHover,
  onSelect,
}: {
  listboxId: string;
  results: SearchResult[];
  isPending: boolean;
  isError: boolean;
  activeIndex: number;
  onHover: (i: number) => void;
  onSelect: (index: number) => void;
}) {
  const { t } = useTranslation();
  if (isPending && results.length === 0) {
    return (
      <div className="flex items-center justify-center gap-2 p-4 text-sm text-text-secondary">
        <Loader2 className="size-4 animate-spin" aria-hidden="true" />
        {t("searching")}
      </div>
    );
  }
  if (isError && results.length === 0) {
    return (
      <div className="p-4 text-sm text-text-secondary" role="alert">
        {t("searchFailed")}
      </div>
    );
  }
  if (results.length === 0) {
    return (
      <div className="p-4 text-sm text-text-secondary" role="status">
        {t("noResults")}
      </div>
    );
  }
  return (
    <>
      {results.map((result, index) => (
        <div
          key={`${result.source}-${result.id}-${index}`}
          id={`${listboxId}-option-${index}`}
          role="option"
          aria-selected={activeIndex === index}
          className={cn(
            "w-full text-left p-2.5 cursor-pointer transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30",
            activeIndex === index ? "bg-hover" : "hoverable:hover:bg-hover",
          )}
          onMouseEnter={() => onHover(index)}
          onMouseDown={(e) => e.preventDefault()}
          onClick={() => onSelect(index)}
        >
          <span className="flex items-center justify-between gap-2">
            <span className="text-sm font-medium text-text-primary truncate">{result.name}</span>
            {typeof result.score === "number" && Number.isFinite(result.score) && (
              <span className="text-xs text-text-secondary ml-2 shrink-0 font-mono">{result.score.toFixed(1)}</span>
            )}
          </span>
          <span className="flex items-center gap-2 mt-1">
            <span className="text-xs text-text-secondary">{t(result.source)}</span>
            {result.provider && <span className="text-xs text-text-tertiary">{result.provider}</span>}
          </span>
        </div>
      ))}
    </>
  );
}
