// src/client/search/SearchInput.tsx
"use client";
import { useCallback, useEffect, useId, useRef, useState } from "react";
import { usePathname, useRouter } from "@/client/router";
import { Loader2, Search, X } from "lucide-react";
import { cn } from "@/client/utils/cn";
import { Input } from "@/client/components/ui/input";
import { useTranslation } from "@/client/providers";
import { useSearchStore } from "@/client/stores";
import type { SearchResult } from "@/shared/types";
import { useSearchAllRankings } from "@/client/search/use-search";
import { useClickOutside, useListKeyboard } from "@/client/search/interaction";

const DEBOUNCE_MS = 200;

export function SearchInput({ className }: { className?: string }) {
  const { t } = useTranslation();
  const router = useRouter();
  const navigate = (to: string) => router.push(to);
  const [isOpen, setIsOpen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const inputId = useId();
  const listboxId = useId();
  const statusId = useId();

  const searchTerm = useSearchStore((s) => s.searchTerm);
  const setSearchTerm = useSearchStore((s) => s.setSearchTerm);
  const pathname = usePathname();
  const [inputValue, setInputValue] = useState(searchTerm);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const cancelDebounce = useCallback(() => {
    if (timerRef.current) {
      clearTimeout(timerRef.current);
      timerRef.current = null;
    }
  }, []);
  const debouncedSetTerm = useCallback(
    (value: string) => {
      cancelDebounce();
      timerRef.current = setTimeout(() => {
        timerRef.current = null;
        setSearchTerm(value);
      }, DEBOUNCE_MS);
    },
    [cancelDebounce, setSearchTerm],
  );
  useEffect(
    () => () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    },
    [],
  );
  // Pathname only: ?tab= switches (replaceState) must preserve the typed query.
  useEffect(() => {
    cancelDebounce();
    setInputValue("");
  }, [pathname, cancelDebounce]);
  useEffect(() => {
    if (inputValue !== searchTerm) debouncedSetTerm(inputValue);
  }, [inputValue, searchTerm, debouncedSetTerm]);

  const { results, isPending, isError } = useSearchAllRankings(searchTerm, { suspended: !isOpen });

  const clearSearch = useCallback(() => {
    cancelDebounce();
    setSearchTerm("");
    setInputValue("");
  }, [setSearchTerm, cancelDebounce]);

  const goToResult = useCallback(
    (result: SearchResult | undefined) => {
      if (!result) return;
      clearSearch();
      navigate(result.link);
      setIsOpen(false);
      setActiveIndex(-1);
    },
    [navigate, clearSearch],
  );

  const handleSelect = useCallback(
    (idx: number) => {
      goToResult(results[idx]);
    },
    [results, goToResult],
  );

  const { clampedIndex, setActiveIndex, handleKeyDown } = useListKeyboard(results.length, handleSelect, () => {
    setIsOpen(false);
    inputRef.current?.focus();
  });

  useClickOutside(containerRef, () => setIsOpen(false));

  const listRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!isOpen || clampedIndex < 0) return;
    listRef.current
      ?.querySelector(`#${CSS.escape(`${listboxId}-option-${clampedIndex}`)}`)
      ?.scrollIntoView({ block: "nearest" });
  }, [clampedIndex, isOpen, listboxId]);

  function onKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (!isOpen && (e.key === "ArrowDown" || e.key === "ArrowUp")) {
      e.preventDefault();
      if (inputValue.length >= 2) setIsOpen(true);
      return;
    }
    if (!isOpen) return;
    handleKeyDown(e);
  }

  let dropdownBody: React.ReactNode;
  if (isPending && results.length === 0) {
    dropdownBody = (
      <div className="flex items-center justify-center gap-2 p-4 text-sm text-text-secondary">
        <Loader2 className="size-4 animate-spin" aria-hidden="true" />
        {t("searching")}
      </div>
    );
  } else if (isError && results.length === 0) {
    dropdownBody = (
      <div className="p-4 text-sm text-text-secondary" role="alert">
        {t("searchFailed")}
      </div>
    );
  } else if (results.length === 0) {
    dropdownBody = (
      <div className="p-4 text-sm text-text-secondary" role="status">
        {t("noResults")}
      </div>
    );
  } else {
    dropdownBody = results.map((result, index) => (
      <button
        key={`${result.source}-${result.id}-${index}`}
        id={`${listboxId}-option-${index}`}
        type="button"
        role="option"
        aria-selected={clampedIndex === index}
        className={cn(
          "w-full text-left p-2.5 rounded-none transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30",
          clampedIndex === index ? "bg-hover" : "hoverable:hover:bg-hover",
        )}
        onMouseEnter={() => setActiveIndex(index)}
        onClick={() => goToResult(result)}
      >
        <span className="flex items-center justify-between gap-2">
          <span className="text-sm font-medium text-text-primary truncate">{result.name}</span>
          {typeof result.score === "number" && Number.isFinite(result.score) && (
            <span className="text-xs text-text-secondary ml-2 shrink-0 font-mono">{result.score.toFixed(1)}</span>
          )}
        </span>
        <span className="flex items-center gap-2 mt-1">
          <span className="text-xs text-text-secondary">{t(result.source)}</span>
          {result.provider && <span className="text-xs text-text-tertiary">{result.provider}</span>}
        </span>
      </button>
    ));
  }

  return (
    <div ref={containerRef} className={cn("relative w-full sm:w-72 min-w-0 max-w-full", className)}>
      <label htmlFor={inputId} className="sr-only">
        {t("searchPlaceholder")}
      </label>
      <div className="flex h-9 items-center gap-2 min-w-0 max-w-full ui-card rounded-none px-3 transition-colors duration-fast focus-within:border-accent/60 focus-within:ring-2 focus-within:ring-ring/30">
        <Search size={16} className="text-text-secondary shrink-0" aria-hidden="true" />
        <Input
          ref={inputRef}
          id={inputId}
          type="text"
          value={inputValue}
          role="combobox"
          aria-expanded={isOpen}
          aria-controls={listboxId}
          aria-activedescendant={clampedIndex >= 0 ? `${listboxId}-option-${clampedIndex}` : undefined}
          aria-autocomplete="list"
          aria-describedby={statusId}
          autoComplete="off"
          onChange={(e) => {
            setInputValue(e.target.value);
            setIsOpen(e.target.value.length >= 2);
            setActiveIndex(-1);
          }}
          onFocus={() => {
            if (inputValue.length >= 2) setIsOpen(true);
          }}
          onKeyDown={onKeyDown}
          placeholder={t("searchPlaceholder")}
          className="flex-1 border-0 bg-transparent px-0 h-full focus:border-transparent focus:ring-0"
        />
        <button
          type="button"
          aria-label={t("clear")}
          aria-hidden={inputValue ? undefined : true}
          tabIndex={inputValue ? 0 : -1}
          onClick={() => {
            clearSearch();
            setIsOpen(false);
            setActiveIndex(-1);
            inputRef.current?.focus();
          }}
          className={cn(
            "shrink-0 rounded-none p-1 hoverable:hover:bg-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30",
            !inputValue && "invisible pointer-events-none",
          )}
        >
          <X size={14} className="text-text-secondary" />
        </button>
      </div>

      {isOpen && inputValue.length >= 2 && (
        <div
          id={listboxId}
          ref={listRef}
          role="listbox"
          className="absolute top-full left-0 right-0 sm:left-auto sm:right-0 sm:w-72 sm:max-w-[calc(100vw-2rem)] mt-1.5 max-h-[28rem] overflow-y-auto overscroll-contain no-scrollbar ui-overlay-md z-40 animate-fade-in"
        >
          <div className="p-1.5">{dropdownBody}</div>
        </div>
      )}
      <div id={statusId} role="status" aria-live="polite" aria-atomic="true" className="sr-only">
        {isOpen && inputValue.length >= 2 && !isPending && t("searchResultsCount", { count: results.length })}
      </div>
    </div>
  );
}

// src/client/search/search-input.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { Loader2 } from "@lucide/vue";
import { useRouter } from "vue-router";
import { cn } from "@/client/utils/cn";
import { useTranslation } from "@/client/i18n";
import { useRouteSearchTerm } from "@/client/stores";
import { MIN_QUERY, useSearchAllRankings } from "@/client/search/use-search";
import Combobox from "@/client/search/combobox.vue";
import { useCombobox } from "@/client/search/use-combobox";

const props = defineProps<{ class?: string }>();

const { t } = useTranslation();
const router = useRouter();
const isOpen = ref(false);
const isFocused = ref(false);

const { term: searchTerm, setTerm: setSearchTerm } = useRouteSearchTerm();

const { results, isPending, isError } = useSearchAllRankings(searchTerm, {
  suspended: computed(() => !isOpen.value),
  warm: isFocused,
});

const combobox = useCombobox({
  initialValue: searchTerm.value,
  minQuery: MIN_QUERY,
  itemCount: computed(() => results.value.length),
  isOpen,
  isFocused,
  onSelect: (index) => {
    const result = results.value[index];
    if (result) void router.push(result.link);
  },
});

const { listboxId, activeIndex, inputValue, debounced, onHover, onSelectIndex } = combobox;

watch([debounced, searchTerm], () => {
  if (debounced.value !== searchTerm.value) setSearchTerm(debounced.value);
});

const pending = computed(() => isPending.value || inputValue.value !== searchTerm.value);
</script>

<template>
  <Combobox
    :controller="combobox"
    :class="props.class"
    :status="pending ? undefined : t('searchResultsCount', { count: results.length })"
  >
    <div
      v-if="pending && results.length === 0"
      class="flex items-center justify-center gap-2 p-4 text-sm text-text-secondary"
    >
      <Loader2 class="size-4 animate-spin" aria-hidden="true" />
      {{ t("searching") }}
    </div>
    <div v-else-if="isError && results.length === 0" class="p-4 text-sm text-text-secondary" role="alert">
      {{ t("searchFailed") }}
    </div>
    <div v-else-if="results.length === 0" class="p-4 text-sm text-text-secondary" role="status">
      {{ t("noResults") }}
    </div>
    <template v-else>
      <div
        v-for="(result, index) in results"
        :id="`${listboxId}-option-${index}`"
        :key="`${result.source}-${result.id}`"
        role="option"
        :aria-selected="activeIndex === index"
        :class="
          cn(
            'w-full text-left p-2.5 cursor-pointer transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30',
            activeIndex === index ? 'bg-hover' : 'hoverable:hover:bg-hover',
          )
        "
        @mouseenter="onHover(index)"
        @mousedown.prevent
        @click="onSelectIndex(index)"
      >
        <span class="flex items-center justify-between gap-2">
          <span class="text-sm font-medium text-text-primary truncate">{{ result.name }}</span>
          <span
            v-if="typeof result.score === 'number' && Number.isFinite(result.score)"
            class="text-xs text-text-secondary ml-2 shrink-0 font-mono"
          >
            {{ result.score.toFixed(1) }}
          </span>
        </span>
        <span class="flex items-center gap-2 mt-1">
          <span class="text-xs text-text-secondary">{{ t(result.source) }}</span>
          <span v-if="result.provider" class="text-xs text-text-tertiary">{{ result.provider }}</span>
        </span>
      </div>
    </template>
  </Combobox>
</template>
