// src/client/features/releases/releases-view.tsx
import { useCallback, useMemo } from "react";
import { ExternalLink } from "lucide-react";
import { RightAlignedText, col, rightCol, type DataTableColumn } from "@/client/components/data/table/table-columns";
import { SearchableDataTable } from "@/client/components/data/table";
import { useTranslation } from "@/client/providers";
import { formatDate, safeHref } from "@/client/utils/format";
import { useSuspenseClosedReleasesState } from "@/client/api/api-queries";
import { PartialNotice } from "@/client/components/feedback";
import { SuspenseQuery } from "@/client/router/suspense-query";
import { SearchInput } from "@/client/search/search-input";
import { PageContainer, PageHeader } from "@/client/components/layout";
import {
  buildClosedReleaseRows,
  getReleaseRowId,
  getReleaseSearchFields,
  type ReleaseRow,
} from "@/client/utils/release-feed";

function ReleaseModelCell({
  title,
  name,
  line,
  semibold,
}: {
  title: string;
  name: string;
  line: React.ReactNode;
  semibold?: boolean;
}) {
  return (
    <div className="min-w-0">
      <p className={`text-sm truncate ${semibold ? "font-semibold" : "font-medium"}`} title={title}>
        {name}
      </p>
      <div className="flex md:hidden mt-1.5 items-center gap-2">{line}</div>
    </div>
  );
}

const getReleaseRowName = (row: ReleaseRow) => row.name;

function ReleasesContent() {
  const { t, lang } = useTranslation();
  const { items: closedReleases, partial } = useSuspenseClosedReleasesState();

  const rows = useMemo(() => buildClosedReleaseRows(closedReleases), [closedReleases]);

  const dateLabels = useMemo(() => {
    const labels = new Map<string, string>();
    for (const row of rows) labels.set(row.id, formatDate(row.date, lang));
    return labels;
  }, [rows, lang]);

  const columns = useMemo<DataTableColumn<ReleaseRow>[]>(
    () => [
      col("model", t("model"), (row) => (
        <ReleaseModelCell
          title={row.name}
          name={row.name}
          semibold
          line={
            <>
              <span className="text-xs text-text-secondary">{row.provider}</span>
              <span className="ui-meta">{dateLabels.get(row.id)!}</span>
            </>
          }
        />
      )),
      rightCol(
        "provider",
        t("provider"),
        (row) => <RightAlignedText className="text-sm">{row.provider}</RightAlignedText>,
        {
          width: "24%",
          hiddenMd: true,
        },
      ),
      rightCol(
        "releaseDate",
        t("releaseDate"),
        (row) => <span className="ui-mono-value font-normal">{dateLabels.get(row.id)!}</span>,
        { width: "18%", hiddenMd: true },
      ),
    ],
    [t, dateLabels],
  );

  const renderExpanded = useCallback(
    (row: ReleaseRow) => {
      const href = safeHref(row.link);
      if (!href) return null;
      return (
        <div className="flex flex-col gap-3 p-4 sm:p-5">
          <a
            href={href}
            target="_blank"
            rel="noopener noreferrer"
            className="group inline-flex items-center gap-1.5 text-sm text-accent w-fit underline-offset-4 transition-colors duration-fast hoverable:hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30"
          >
            {t("aaModelPage")}
            <ExternalLink
              size={14}
              className="md:opacity-0 md:group-hover:opacity-100 transition-opacity duration-fast"
            />
          </a>
        </div>
      );
    },
    [t],
  );

  return (
    <PageContainer>
      <PageHeader title={t("releases")} description={t("releaseDataSources")} actions={<SearchInput />} />
      <div className="flex items-center gap-2 -mt-2 mb-4">
        <span className="ui-meta tabular-nums">{t("events", { count: rows.length })}</span>
      </div>
      {partial && <PartialNotice />}
      <SearchableDataTable
        data={rows}
        columns={columns}
        getRowId={getReleaseRowId}
        getRowName={getReleaseRowName}
        getSearchFields={getReleaseSearchFields}
        renderExpandedRow={renderExpanded}
      />
    </PageContainer>
  );
}

export function ReleasesView() {
  return (
    <SuspenseQuery resetKey="releases">
      <ReleasesContent />
    </SuspenseQuery>
  );
}

// src/client/features/releases/releases-view.vue
<script setup lang="ts">
import { computed, defineComponent, h, type VNodeChild } from "vue";
import { ExternalLink } from "@lucide/vue";
import {
  col,
  rightCol,
  RightAlignedText,
  type DataTableColumn,
} from "@/client/components/data/table/table-columns.vue";
import SearchableDataTable from "@/client/components/data/table/data-table.vue";
import PageContainer from "@/client/components/layout/page-container.vue";
import PageHeader from "@/client/components/layout/page-header.vue";
import PartialNotice from "@/client/components/feedback/partial-notice.vue";
import SuspenseQuery from "@/client/router/suspense-query.vue";
import SearchInput from "@/client/search/search-input.vue";
import { useTranslation } from "@/client/i18n";
import { useSuspenseClosedReleasesState } from "@/client/api/api-queries";
import { formatDate, safeHref } from "@/client/utils/format";
import {
  buildClosedReleaseRows,
  getReleaseRowId,
  getReleaseSearchFields,
  type ReleaseRow,
} from "@/client/utils/release-feed";

const { t } = useTranslation();

const getReleaseRowName = (row: ReleaseRow) => row.name;

const ReleasesData = defineComponent({
  async setup(_props, { slots }) {
    const { t: translate, lang } = useTranslation();
    const state = await useSuspenseClosedReleasesState();

    const rows = computed(() => buildClosedReleaseRows(state.value.items));

    const dateLabels = computed(() => {
      const labels = new Map<string, string>();
      for (const row of rows.value) labels.set(row.id, formatDate(row.date, lang.value));
      return labels;
    });

    const columns = computed<DataTableColumn<ReleaseRow>[]>(() => [
      col("model", translate("model"), (row) =>
        h("div", { class: "min-w-0" }, [
          h("p", { class: "text-sm truncate font-semibold", title: row.name }, row.name),
          h("div", { class: "flex md:hidden mt-1.5 items-center gap-2" }, [
            h("span", { class: "text-xs text-text-secondary" }, row.provider),
            h("span", { class: "ui-meta" }, dateLabels.value.get(row.id)!),
          ]),
        ]),
      ),
      rightCol(
        "provider",
        translate("provider"),
        (row) => h(RightAlignedText, { class: "text-sm" }, () => row.provider),
        {
          width: "24%",
          hiddenMd: true,
        },
      ),
      rightCol(
        "releaseDate",
        translate("releaseDate"),
        (row) => h("span", { class: "ui-mono-value font-normal" }, dateLabels.value.get(row.id)!),
        { width: "18%", hiddenMd: true },
      ),
    ]);

    function renderExpandedRow(row: ReleaseRow): VNodeChild {
      const href = safeHref(row.link);
      if (!href) return null;
      return h("div", { class: "flex flex-col gap-3 p-4 sm:p-5" }, [
        h(
          "a",
          {
            href,
            target: "_blank",
            rel: "noopener noreferrer",
            class:
              "group inline-flex items-center gap-1.5 text-sm text-accent w-fit underline-offset-4 transition-colors duration-fast hoverable:hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30",
          },
          [
            translate("aaModelPage"),
            h(ExternalLink, {
              size: 14,
              class: "md:opacity-0 md:group-hover:opacity-100 transition-opacity duration-fast",
            }),
          ],
        ),
      ]);
    }

    return () =>
      slots.default?.({
        rows: rows.value,
        partial: state.value.partial,
        columns: columns.value,
        renderExpandedRow,
      }) ?? null;
  },
});
</script>

<template>
  <PageContainer>
    <PageHeader :title="t('releases')" :description="t('releaseDataSources')">
      <template #actions>
        <SearchInput />
      </template>
    </PageHeader>
    <SuspenseQuery>
      <ReleasesData>
        <template #default="{ rows, partial, columns, renderExpandedRow }">
          <div class="flex items-center gap-2 -mt-2 mb-4">
            <span class="ui-meta tabular-nums">{{ t("events", { count: rows.length }) }}</span>
          </div>
          <PartialNotice v-if="partial" />
          <SearchableDataTable
            :data="rows"
            :columns="columns"
            :get-row-id="getReleaseRowId"
            :get-row-name="getReleaseRowName"
            :get-search-fields="getReleaseSearchFields"
            :render-expanded-row="renderExpandedRow"
          />
        </template>
      </ReleasesData>
    </SuspenseQuery>
  </PageContainer>
</template>
