// src/client/features/releases/releases-view.vue
<script setup lang="ts">
import { computed, defineComponent, h, type VNodeChild } from "vue";
import { ExternalLink } from "@lucide/vue";
import {
  col,
  rightCol,
  RightAlignedText,
  type DataTableColumn,
} from "@/client/components/data/table/table-columns.vue";
import SearchableDataTable from "@/client/components/data/table/data-table.vue";
import PageContainer from "@/client/components/layout/page-container.vue";
import PageHeader from "@/client/components/layout/page-header.vue";
import PartialNotice from "@/client/components/feedback/partial-notice.vue";
import SuspenseQuery from "@/client/router/suspense-query.vue";
import SearchInput from "@/client/search/search-input.vue";
import { useTranslation } from "@/client/i18n";
import { useSuspenseClosedReleasesState } from "@/client/api/api-queries";
import { formatDate, safeHref } from "@/client/utils/format";
import {
  buildClosedReleaseRows,
  getReleaseRowId,
  getReleaseSearchFields,
  type ReleaseRow,
} from "@/shared/utils/release-feed";

const { t } = useTranslation();

const getReleaseRowName = (row: ReleaseRow) => row.name;

const ReleasesData = defineComponent({
  async setup(_props, { slots }) {
    const { t: translate, lang } = useTranslation();
    const state = await useSuspenseClosedReleasesState();

    const rows = computed(() => buildClosedReleaseRows(state.value.items));

    const dateLabels = computed(() => {
      const labels = new Map<string, string>();
      for (const row of rows.value) labels.set(row.id, formatDate(row.date, lang.value));
      return labels;
    });

    const columns = computed<DataTableColumn<ReleaseRow>[]>(() => [
      col("model", translate("model"), (row) =>
        h("div", { class: "min-w-0" }, [
          h("p", { class: "text-sm truncate font-semibold", title: row.name }, row.name),
          h("div", { class: "flex md:hidden mt-1.5 items-center gap-2" }, [
            h("span", { class: "text-xs text-text-secondary" }, row.provider),
            h("span", { class: "ui-meta" }, dateLabels.value.get(row.id)!),
          ]),
        ]),
      ),
      rightCol(
        "provider",
        translate("provider"),
        (row) => h(RightAlignedText, { class: "text-sm" }, () => row.provider),
        {
          width: "24%",
          hiddenMd: true,
        },
      ),
      rightCol(
        "releaseDate",
        translate("releaseDate"),
        (row) => h("span", { class: "ui-mono-value font-normal" }, dateLabels.value.get(row.id)!),
        { width: "18%", hiddenMd: true },
      ),
    ]);

    function renderExpandedRow(row: ReleaseRow): VNodeChild {
      const href = safeHref(row.link);
      if (!href) return null;
      return h("div", { class: "flex flex-col gap-3 p-4 sm:p-5" }, [
        h(
          "a",
          {
            href,
            target: "_blank",
            rel: "noopener noreferrer",
            class:
              "group inline-flex items-center gap-1.5 text-sm text-accent w-fit underline-offset-4 transition-colors duration-fast hoverable:hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30",
          },
          [
            translate("aaModelPage"),
            h(ExternalLink, {
              size: 14,
              class: "md:opacity-0 md:group-hover:opacity-100 transition-opacity duration-fast",
            }),
          ],
        ),
      ]);
    }

    return () =>
      slots.default?.({
        rows: rows.value,
        partial: state.value.partial,
        columns: columns.value,
        renderExpandedRow,
      }) ?? null;
  },
});
</script>

<template>
  <PageContainer>
    <PageHeader :title="t('releases')" :description="t('releaseDataSources')">
      <template #actions>
        <SearchInput />
      </template>
    </PageHeader>
    <SuspenseQuery>
      <ReleasesData>
        <template #default="{ rows, partial, columns, renderExpandedRow }">
          <div class="flex items-center gap-2 -mt-2 mb-4">
            <span class="ui-meta tabular-nums">{{ t("events", { count: rows.length }) }}</span>
          </div>
          <PartialNotice v-if="partial" />
          <SearchableDataTable
            :data="rows"
            :columns="columns"
            :get-row-id="getReleaseRowId"
            :get-row-name="getReleaseRowName"
            :get-search-fields="getReleaseSearchFields"
            :render-expanded-row="renderExpandedRow"
          />
        </template>
      </ReleasesData>
    </SuspenseQuery>
  </PageContainer>
</template>

// src/client/features/releases/ReleasesView.tsx
"use client";
import { useMemo } from "react";
import { ExternalLink } from "lucide-react";
import { RightAlignedText, type DataTableColumn } from "@/client/components/data/columns";
import { SearchableDataTable } from "@/client/components/data/searchable";
import { useTranslation } from "@/client/providers";
import type { TranslationKey } from "@/shared/i18n";
import { formatDate, safeHref } from "@/client/utils/format";
import { useSuspenseClosedReleasesState, useSuspenseOpenSourceReleases } from "@/client/api/queries";
import { SuspenseQuery, PartialNotice } from "@/client/components/feedback";
import { SearchInput } from "@/client/search/SearchInput";
import { TabbedPage } from "@/client/components/layout";
import { useClientTab } from "@/client/hooks/use-client-tab";
import { type TabItem } from "@/client/components/ui/tabs";
import type { ClosedReleaseEntry } from "@/shared/types";
import {
  buildReleaseFeedEntries,
  getFeedRowId,
  getFeedSearchFields,
  parseReleaseTs as parseTs,
  type FeedEntry,
  type FeedEntryType,
} from "@/client/features/releases/feed-entries";

function useReleaseFeedEntries(openSourceReleases: Parameters<typeof buildReleaseFeedEntries>[0]): FeedEntry[] {
  return useMemo(() => buildReleaseFeedEntries(openSourceReleases), [openSourceReleases]);
}

function ReleaseModelCell({
  title,
  name,
  line,
  semibold,
}: {
  title: string;
  name: string;
  line: React.ReactNode;
  semibold?: boolean;
}) {
  return (
    <div className="min-w-0">
      <p className={`text-sm truncate ${semibold ? "font-semibold" : "font-medium"}`} title={title}>
        {name}
      </p>
      <div className="flex md:hidden mt-1.5 items-center gap-2">{line}</div>
    </div>
  );
}

function releaseDateCol<T>(t: ReturnType<typeof useTranslation>["t"], lang: string, getDate: (row: T) => string) {
  return {
    header: t("releaseDate"),
    align: "right" as const,
    hiddenMd: true,
    cell: (row: T) => <span className="ui-mono-value font-normal">{formatDate(getDate(row), lang)}</span>,
  };
}

function FeedTab({ allEntries }: { allEntries: FeedEntry[] }) {
  const { t, lang } = useTranslation();

  const feedColumns = useMemo<DataTableColumn<FeedEntry>[]>(() => {
    const TYPE_LABEL: Record<FeedEntryType, TranslationKey> = {
      update: "releaseUpdate",
      opensource: "releaseOpenSource",
    };
    return [
      {
        id: "model",
        header: t("model"),
        cell: (row) => (
          <ReleaseModelCell
            title={row.name}
            name={row.name}
            line={
              <>
                <span className="text-xs font-medium text-text-secondary">{t(TYPE_LABEL[row.type])}</span>
                <span className="ui-meta">{formatDate(row.date, lang)}</span>
              </>
            }
          />
        ),
      },
      {
        id: "date",
        width: 120,
        ...releaseDateCol(t, lang, (row: FeedEntry) => row.date),
      },
      {
        id: "type",
        header: t("releaseType"),
        align: "right",
        width: 140,
        hiddenMd: true,
        cell: (row) => <span className="text-xs font-medium text-text-secondary">{t(TYPE_LABEL[row.type])}</span>,
      },
    ];
  }, [t, lang]);

  return (
    <SearchableDataTable
      data={allEntries}
      columns={feedColumns}
      getRowId={getFeedRowId}
      getSearchFields={getFeedSearchFields}
    />
  );
}

interface ClosedRow {
  entry: ClosedReleaseEntry;
  ts: number;
}

const getClosedRowId = (row: ClosedRow) => row.entry.id;
const getClosedSearchFields = (row: ClosedRow) => [row.entry.model, row.entry.provider];

function ClosedReleasesTab({ releases, partial }: { releases: ClosedReleaseEntry[]; partial: boolean }) {
  const { t, lang } = useTranslation();

  const rows = useMemo<ClosedRow[]>(
    () =>
      releases
        .map((entry) => {
          const ts = parseTs(entry.releaseDate);
          return ts == null ? null : { entry, ts };
        })
        .filter((x): x is ClosedRow => x != null)
        .sort((a, b) => b.ts - a.ts),
    [releases],
  );

  const columns = useMemo<DataTableColumn<ClosedRow>[]>(
    () => [
      {
        id: "model",
        header: t("model"),
        cell: (row) => (
          <ReleaseModelCell
            title={row.entry.model}
            name={row.entry.model}
            semibold
            line={
              <>
                <span className="text-xs text-text-secondary">{row.entry.provider}</span>
                <span className="ui-meta">{formatDate(row.entry.releaseDate, lang)}</span>
              </>
            }
          />
        ),
      },
      {
        id: "provider",
        header: t("provider"),
        align: "right",
        width: "24%",
        hiddenMd: true,
        cell: (row) => <RightAlignedText className="text-sm">{row.entry.provider}</RightAlignedText>,
      },
      {
        id: "releaseDate",
        width: "18%",
        ...releaseDateCol(t, lang, (row: ClosedRow) => row.entry.releaseDate),
      },
    ],
    [t, lang],
  );

  const renderExpanded = (row: ClosedRow) => {
    const href = safeHref(row.entry.link);
    return (
      <div className="flex flex-col gap-3 p-4 sm:p-5">
        {href && (
          <a
            href={href}
            target="_blank"
            rel="noopener noreferrer"
            className="group inline-flex items-center gap-1.5 text-sm text-accent w-fit underline-offset-4 transition-colors duration-fast hoverable:hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 rounded-none"
          >
            {t("aaModelPage")}
            <ExternalLink
              size={14}
              className="md:opacity-0 md:group-hover:opacity-100 transition-opacity duration-fast"
            />
          </a>
        )}
      </div>
    );
  };

  return (
    <>
      {partial && (
        <div className="mb-3">
          <PartialNotice message={t("partialDataNotice")} />
        </div>
      )}
      <SearchableDataTable
        data={rows}
        columns={columns}
        getRowId={getClosedRowId}
        getSearchFields={getClosedSearchFields}
        renderExpandedRow={renderExpanded}
      />
    </>
  );
}

const TAB_IDS = ["feed", "closed"] as const;

function ReleasesContent() {
  const { t } = useTranslation();
  const [mode, setMode] = useClientTab("tab", TAB_IDS, TAB_IDS[0]);
  const openSourceReleases = useSuspenseOpenSourceReleases();
  const { items: closedReleases, partial: closedPartial } = useSuspenseClosedReleasesState();

  const allEntries = useReleaseFeedEntries(openSourceReleases);

  const tabs: TabItem[] = useMemo(
    () => [
      { id: "feed", label: t("releaseOpenSource") },
      { id: "closed", label: t("releaseClosedSource") },
    ],
    [t],
  );

  const countLabel =
    mode === "feed" ? t("events", { count: allEntries.length }) : t("modelsTotal", { count: closedReleases.length });
  const description = mode === "feed" ? t("releaseDataSource") : t("closedReleasesSource");

  return (
    <TabbedPage
      title={t("releases")}
      kicker={t("kickerReleases")}
      description={description}
      actions={<SearchInput />}
      countLabel={countLabel}
      tabs={tabs}
      activeTab={mode}
      onTabChange={setMode}
    >
      {mode === "feed" ? (
        <FeedTab allEntries={allEntries} />
      ) : (
        <ClosedReleasesTab releases={closedReleases} partial={closedPartial} />
      )}
    </TabbedPage>
  );
}

export function ReleasesView() {
  return (
    <SuspenseQuery resetKey="releases">
      <ReleasesContent />
    </SuspenseQuery>
  );
}
