// src/client/components/data/table/data-table.tsx
import { memo, useDeferredValue, useMemo, useRef, useState, type ReactNode } from "react";
import { useDevice, useTranslation } from "@/client/providers";
import { EmptyState } from "@/client/components/feedback";
import { Pagination } from "@/client/components/ui/pagination";
import type { DataTableColumn, RowListProps } from "@/client/components/data/table/table-columns";
import { filterByTerm } from "@/client/search/match";
import { useRouteSearchTerm } from "@/client/stores";
import { DEFAULT_PAGE_SIZE, MOBILE_PAGE_SIZE, usePagedData } from "./paging";
import { TableBody, TableHeader } from "./desktop";
import { MobileTableBody } from "./mobile";

interface DataTableProps<T> {
  data: T[];
  columns: DataTableColumn<T>[];
  getRowId: (row: T) => string;
  getRowName?: (row: T) => string;
  renderExpandedRow?: (row: T) => ReactNode;
  resetKey?: string | number;
}

function DataTableInner<T>({ data, columns, getRowId, getRowName, renderExpandedRow, resetKey }: DataTableProps<T>) {
  const { isMobile } = useDevice();
  const { t } = useTranslation();
  const [ownExpandedId, setOwnExpandedId] = useState<string | null>(null);
  const isExpandable = !!renderExpandedRow;
  const { dedupedData, page, totalPages, pagedData, goToPage } = usePagedData(
    data,
    getRowId,
    isMobile ? MOBILE_PAGE_SIZE : DEFAULT_PAGE_SIZE,
    resetKey,
  );
  const rootRef = useRef<HTMLDivElement>(null);

  const expandedRowGone = useMemo(
    () => ownExpandedId != null && !dedupedData.some((row) => getRowId(row) === ownExpandedId),
    [dedupedData, getRowId, ownExpandedId],
  );
  if (expandedRowGone) {
    setOwnExpandedId(null);
  }

  const handlePageChange = (p: number) => {
    goToPage(p);
    setOwnExpandedId(null);
    rootRef.current?.querySelector<HTMLElement>("[data-table-top]")?.focus?.();
  };

  const pagination =
    totalPages > 1 ? (
      <Pagination page={page} totalPages={totalPages} onChange={handlePageChange} className="justify-center" />
    ) : null;
  const listProps: RowListProps<T> = useMemo(
    () => ({
      pagedData,
      columns,
      getRowId,
      getRowName,
      isExpandable,
      expandedRowId: ownExpandedId,
      onToggleExpand: setOwnExpandedId,
      renderExpandedRow,
    }),
    [pagedData, columns, getRowId, getRowName, isExpandable, ownExpandedId, renderExpandedRow],
  );

  return (
    <div ref={rootRef} className="flex flex-col gap-4 min-w-0">
      <span data-table-top tabIndex={-1} className="outline-none" aria-hidden="true" />
      {dedupedData.length === 0 ? (
        <EmptyState message={t("noResults")} />
      ) : isMobile ? (
        <>
          <MobileTableBody {...listProps} />
          {pagination}
        </>
      ) : (
        <>
          <div className="ui-card overflow-x-auto">
            <table className="w-full text-sm table-fixed">
              <TableHeader columns={columns} isExpandable={isExpandable} />
              <TableBody {...listProps} />
            </table>
          </div>
          {pagination}
        </>
      )}
    </div>
  );
}

const DataTable = memo(DataTableInner) as typeof DataTableInner;

interface SearchableDataTableProps<T> extends Omit<DataTableProps<T>, "data"> {
  data: T[];
  getSearchFields: (row: T) => (string | null | undefined)[];
}

function SearchableDataTableInner<T>({ data, getSearchFields, ...tableProps }: SearchableDataTableProps<T>) {
  const { term: searchTerm } = useRouteSearchTerm();
  const deferredTerm = useDeferredValue(searchTerm);
  const filtered = useMemo(
    () => filterByTerm(data, deferredTerm, getSearchFields),
    [data, deferredTerm, getSearchFields],
  );
  return <DataTable data={filtered} resetKey={deferredTerm} {...tableProps} />;
}

export const SearchableDataTable = memo(SearchableDataTableInner) as typeof SearchableDataTableInner;

// src/client/components/data/table/data-table.vue
<script setup lang="ts" generic="T">
import { computed, ref, useSlots, watch, type VNodeChild } from "vue";
import EmptyState from "@/client/components/feedback/empty-state.vue";
import Pagination from "@/client/components/ui/pagination.vue";
import { useTranslation } from "@/client/i18n";
import { useDevice } from "@/client/device";
import { filterByTerm } from "@/client/search/match";
import { useRouteSearchTerm } from "@/client/stores";
import type { DataTableColumn } from "./table-columns.vue";
import { DEFAULT_PAGE_SIZE, MOBILE_PAGE_SIZE, usePagedData } from "./paging";
import TableBody, { TableHeader } from "./desktop.vue";
import MobileTableBody from "./mobile.vue";

const props = defineProps<{
  data: T[];
  columns: DataTableColumn<T>[];
  getRowId: (row: T) => string;
  getRowName?: (row: T) => string;
  getSearchFields: (row: T) => (string | null | undefined)[];
  renderExpandedRow?: (row: T) => VNodeChild;
}>();

defineSlots<{ expandedRow?: (props: { row: T }) => VNodeChild }>();

const slots = useSlots();
const isMobile = useDevice();
const { t } = useTranslation();
const { term } = useRouteSearchTerm();

const filtered = computed(() => filterByTerm(props.data, term.value, props.getSearchFields));
const expandedId = ref<string | null>(null);
const isExpandable = computed(() => props.renderExpandedRow != null || slots.expandedRow != null);
const renderExpanded = computed<(row: T) => VNodeChild>(
  () => props.renderExpandedRow ?? ((row: T) => slots.expandedRow?.({ row }) ?? null),
);
const rootEl = ref<HTMLDivElement | null>(null);

const { dedupedData, page, totalPages, pagedData, goToPage } = usePagedData(
  () => filtered.value,
  (row: T) => props.getRowId(row),
  () => (isMobile.value ? MOBILE_PAGE_SIZE : DEFAULT_PAGE_SIZE),
  () => term.value,
);

const expandedRowGone = computed(
  () => expandedId.value != null && !dedupedData.value.some((row) => props.getRowId(row) === expandedId.value),
);

watch(
  expandedRowGone,
  (gone) => {
    if (gone) expandedId.value = null;
  },
  { immediate: true },
);

function setExpandedId(rowId: string | null): void {
  expandedId.value = rowId;
}

function handlePageChange(p: number): void {
  goToPage(p);
  expandedId.value = null;
  rootEl.value?.querySelector<HTMLElement>("[data-table-top]")?.focus();
}
</script>

<template>
  <div ref="rootEl" class="flex flex-col gap-4 min-w-0">
    <span data-table-top="true" tabindex="-1" class="outline-none" aria-hidden="true" />
    <EmptyState v-if="dedupedData.length === 0" :message="t('noResults')" />
    <template v-else-if="isMobile">
      <MobileTableBody
        :paged-data="pagedData"
        :columns="columns"
        :get-row-id="getRowId"
        :get-row-name="getRowName"
        :is-expandable="isExpandable"
        :expanded-row-id="expandedId"
        :render-expanded-row="renderExpanded"
        @toggle-expand="setExpandedId"
      />
      <Pagination :page="page" :total-pages="totalPages" @change="handlePageChange" />
    </template>
    <template v-else>
      <div class="ui-card overflow-x-auto">
        <table class="w-full text-sm table-fixed">
          <TableHeader :columns="columns" :is-expandable="isExpandable" />
          <TableBody
            :paged-data="pagedData"
            :columns="columns"
            :get-row-id="getRowId"
            :get-row-name="getRowName"
            :is-expandable="isExpandable"
            :expanded-row-id="expandedId"
            :render-expanded-row="renderExpanded"
            @toggle-expand="setExpandedId"
          />
        </table>
      </div>
      <Pagination :page="page" :total-pages="totalPages" @change="handlePageChange" />
    </template>
  </div>
</template>
