// src/client/components/data/table/mobile.tsx
import { Fragment, memo } from "react";
import type { DataTableColumn, RowListProps } from "@/client/components/data/table/table-columns";
import { ExpandToggle, getRowExpandState } from "./row-expand";
import { cn } from "@/client/utils/cn";

interface MobileColumnLayout<T> {
  primaryCol: DataTableColumn<T>;
  mainStatCol?: DataTableColumn<T>;
  secondaryCols: DataTableColumn<T>[];
}

function resolveMobileColumns<T>(columns: DataTableColumn<T>[]): MobileColumnLayout<T> | null {
  if (columns.length === 0) return null;
  const primaryCol = columns.find((col) => !col.hiddenMd) ?? (columns[0] as DataTableColumn<T>);
  const others = columns.filter((col) => col !== primaryCol);
  const mainStatCol = others.find((col) => col.mobilePrimary) ?? others.find((col) => !col.hiddenMd);
  const secondaryCols = others.filter((col) => !col.hiddenMd && col !== mainStatCol);
  return { primaryCol, mainStatCol, secondaryCols };
}

function MobileTableBodyInner<T>({
  pagedData,
  columns,
  getRowId,
  getRowName,
  isExpandable,
  expandedRowId,
  onToggleExpand,
  renderExpandedRow,
}: RowListProps<T>) {
  const layout = resolveMobileColumns(columns);
  if (!layout) return null;
  const { primaryCol, mainStatCol, secondaryCols } = layout;
  return (
    <div className="flex flex-col gap-3">
      {pagedData.map((row) => {
        const { rowId, isExpanded, toggle } = getRowExpandState(row, getRowId, expandedRowId, onToggleExpand);
        return (
          <Fragment key={rowId}>
            <div
              className={cn(
                "border border-border bg-bg-card p-4 overflow-hidden transition-colors duration-fast",
                "hoverable:hover:border-text-tertiary/40",
                isExpanded && "border-text-tertiary/40",
              )}
            >
              <div className="flex items-center gap-2 min-w-0">
                {isExpandable ? (
                  <ExpandToggle
                    isExpanded={isExpanded}
                    onToggle={toggle}
                    rowName={getRowName?.(row) ?? rowId}
                    size={16}
                    controlsId={`${rowId}-panel`}
                  />
                ) : null}
                <div className="min-w-0 flex-1">{primaryCol?.cell(row)}</div>
                {mainStatCol && (
                  <div className="shrink-0 text-right min-w-0 max-w-[40%]">
                    {mainStatCol.header && <span className="ui-meta mr-1.5 truncate">{mainStatCol.header}</span>}
                    <div className="ui-mono-value font-semibold">{mainStatCol.cell(row)}</div>
                  </div>
                )}
              </div>
              {secondaryCols.length > 0 && (
                <div className="flex flex-wrap gap-x-4 gap-y-1.5 mt-3 border-t border-border/60 pt-3">
                  {secondaryCols.map((col) => (
                    <div
                      key={col.id}
                      className={cn("flex items-baseline gap-1.5 min-w-0", col.align === "right" && "ml-auto")}
                    >
                      {col.header && <span className="ui-meta shrink-0">{col.header}</span>}
                      <div className="ui-body min-w-0">{col.cell(row)}</div>
                    </div>
                  ))}
                </div>
              )}
            </div>
            {isExpanded && renderExpandedRow && (
              <div
                id={`${rowId}-panel`}
                role="region"
                className="border border-t-0 border-border bg-bg-secondary/60 px-4 py-3 overflow-hidden animate-slide-up"
              >
                {renderExpandedRow(row)}
              </div>
            )}
          </Fragment>
        );
      })}
    </div>
  );
}

export const MobileTableBody = memo(MobileTableBodyInner) as typeof MobileTableBodyInner;

// src/client/components/data/table/mobile.vue
<script setup lang="ts" generic="T">
import { computed, type VNodeChild } from "vue";
import type { DataTableColumn, RowListProps } from "./table-columns.vue";
import ExpandToggle, { ExpandedRowPanel } from "./row-expand.vue";
import { cn } from "@/client/utils/cn";

interface MobileColumnLayout<T> {
  primaryCol: DataTableColumn<T>;
  mainStatCol?: DataTableColumn<T>;
  secondaryCols: DataTableColumn<T>[];
}

const props = defineProps<RowListProps<T>>();

const emit = defineEmits<{ toggleExpand: [rowId: string | null] }>();

function resolveMobileColumns(columns: DataTableColumn<T>[]): MobileColumnLayout<T> | null {
  if (columns.length === 0) return null;
  const primaryCol = columns.find((col) => !col.hiddenMd) ?? (columns[0] as DataTableColumn<T>);
  const others = columns.filter((col) => col !== primaryCol);
  const mainStatCol = others.find((col) => col.mobilePrimary) ?? others.find((col) => !col.hiddenMd);
  const secondaryCols = others.filter((col) => !col.hiddenMd && col !== mainStatCol);
  return { primaryCol, mainStatCol, secondaryCols };
}

const layout = computed(() => resolveMobileColumns(props.columns));

const CellView = (cellProps: { render: (row: T) => VNodeChild; row: T }): VNodeChild =>
  cellProps.render(cellProps.row);

const renderExpanded = (row: T): VNodeChild => props.renderExpandedRow?.(row);
const rowName = (row: T): string => props.getRowName?.(row) ?? props.getRowId(row);
const isRowExpanded = (row: T): boolean => props.expandedRowId === props.getRowId(row);
</script>

<template>
  <div v-if="layout" class="flex flex-col gap-3">
    <template v-for="row in pagedData" :key="getRowId(row)">
      <div
        :class="
          cn(
            'border border-border bg-bg-card p-4 overflow-hidden transition-colors duration-fast',
            'hoverable:hover:border-text-tertiary/40',
            isRowExpanded(row) && 'border-text-tertiary/40',
          )
        "
      >
        <div class="flex items-center gap-2 min-w-0">
          <ExpandToggle
            v-if="isExpandable"
            :row-id="getRowId(row)"
            :row-name="rowName(row)"
            :is-expanded="isRowExpanded(row)"
            :size="16"
            @toggle-expand="emit('toggleExpand', $event)"
          />
          <div class="min-w-0 flex-1">
            <CellView :render="layout.primaryCol.cell" :row="row" />
          </div>
          <div v-if="layout.mainStatCol" class="shrink-0 text-right min-w-0 max-w-[40%]">
            <span v-if="layout.mainStatCol.header" class="ui-meta mr-1.5 truncate">{{ layout.mainStatCol.header }}</span>
            <div class="ui-mono-value font-semibold">
              <CellView :render="layout.mainStatCol.cell" :row="row" />
            </div>
          </div>
        </div>
        <div
          v-if="layout.secondaryCols.length > 0"
          class="flex flex-wrap gap-x-4 gap-y-1.5 mt-3 border-t border-border/60 pt-3"
        >
          <div
            v-for="col in layout.secondaryCols"
            :key="col.id"
            :class="cn('flex items-baseline gap-1.5 min-w-0', col.align === 'right' && 'ml-auto')"
          >
            <span v-if="col.header" class="ui-meta shrink-0">{{ col.header }}</span>
            <div class="ui-body min-w-0">
              <CellView :render="col.cell" :row="row" />
            </div>
          </div>
        </div>
      </div>
      <ExpandedRowPanel
        v-if="isRowExpanded(row) && isExpandable"
        :row-id="getRowId(row)"
        :row-name="rowName(row)"
        class="border border-t-0 border-border bg-bg-secondary/60 overflow-hidden"
      >
        <CellView :render="renderExpanded" :row="row" />
      </ExpandedRowPanel>
    </template>
  </div>
</template>
