// src/client/features/compare/price-compare/estimator.vue
<script setup lang="ts">
import { computed } from "vue";
import { approxEq } from "@/shared/utils";
import { modelDisplayName, modelId } from "@/client/utils/model-utils";
import { formatDollar } from "@/client/utils/format";
import { cn } from "@/client/utils/cn";
import type { ArtificialAnalysisModel } from "@/shared/types";
import Card from "@/client/components/ui/card.vue";
import CardContent from "@/client/components/ui/card-content.vue";
import CardHeader from "@/client/components/ui/card-header.vue";
import { useTranslation } from "@/client/i18n";
import { seriesColor, useChartTheme } from "@/client/theme/chart-theme";
import { useMonthlyCosts } from "@/client/pricing/cost-inputs";
import CostEstimatorInputs from "@/client/pricing/cost-form.vue";
import { WinnerMark } from "@/client/features/compare/compare-table.vue";
import { modelKeyOf } from "@/client/features/compare/compare-logic";

const props = defineProps<{ models: ArtificialAnalysisModel[] }>();

const { t } = useTranslation();
const theme = useChartTheme();

const costState = useMonthlyCosts(() => props.models);
const monthlyCosts = costState.monthlyCosts;

const bestMonthlyCost = computed(() => {
  const valid = [...monthlyCosts.value.values()].filter((v): v is number => v !== null);
  return valid.length > 0 ? Math.min(...valid) : null;
});

function costOf(model: ArtificialAnalysisModel): number | null {
  return monthlyCosts.value.get(modelId(model)) ?? null;
}

function isBestCost(model: ArtificialAnalysisModel): boolean {
  const cost = costOf(model);
  return cost != null && bestMonthlyCost.value != null && approxEq(cost, bestMonthlyCost.value);
}
</script>

<template>
  <Card>
    <CardContent>
      <CardHeader :title="t('estimatedMonthlyCost')" />
      <div class="flex flex-col sm:flex-row flex-wrap gap-3 sm:gap-4 mb-5">
        <CostEstimatorInputs :state="costState" layout="label-input-unit" />
      </div>
      <div class="flex flex-col gap-3">
        <div
          v-for="(model, index) in props.models"
          :key="modelKeyOf(model, index)"
          class="flex items-center justify-between gap-2"
        >
          <span class="text-sm truncate" :style="{ color: seriesColor(theme, index) }">
            {{ modelDisplayName(model) }}
          </span>
          <span v-if="costOf(model) != null" :class="cn('font-mono text-sm', isBestCost(model) && 'font-semibold text-success')">
            {{ formatDollar(costOf(model), t) }}
            <WinnerMark v-if="isBestCost(model)" />
          </span>
          <span v-else class="text-sm text-text-tertiary">{{ t("notAvailable") }}</span>
        </div>
      </div>
    </CardContent>
  </Card>
</template>

// src/client/features/compare/price-compare/estimator.tsx
import { memo, useMemo } from "react";
import { approxEq } from "@/shared/utils";
import { modelDisplayName, modelId } from "@/client/utils/model-utils";
import { formatDollar } from "@/client/utils/format";
import { cn } from "@/client/utils/cn";
import type { ArtificialAnalysisModel } from "@/shared/types";
import { Card, CardContent, CardHeader } from "@/client/components/ui/card";
import { useTranslation } from "@/client/providers";
import { useChartTheme, seriesColor } from "@/client/theme/chart-theme";
import { useMonthlyCosts } from "@/client/pricing/cost-inputs";
import { CostEstimatorInputs } from "@/client/pricing/cost-form";
import { WinnerMark } from "@/client/features/compare/compare-table";

export const CostEstimator = memo(function CostEstimator({ models }: { models: ArtificialAnalysisModel[] }) {
  const { t } = useTranslation();
  const theme = useChartTheme();

  const costState = useMonthlyCosts(models);
  const { monthlyCosts } = costState;
  const bestMonthlyCost = useMemo(() => {
    const valid = [...monthlyCosts.values()].filter((v): v is number => v !== null);
    return valid.length > 0 ? Math.min(...valid) : null;
  }, [monthlyCosts]);

  return (
    <Card>
      <CardContent>
        <CardHeader title={t("estimatedMonthlyCost")} />
        <div className="flex flex-col sm:flex-row flex-wrap gap-3 sm:gap-4 mb-5">
          <CostEstimatorInputs state={costState} layout="label-input-unit" />
        </div>
        <div className="flex flex-col gap-3">
          {models.map((model, index) => {
            const cost = monthlyCosts.get(modelId(model)) ?? null;
            const isBest = cost != null && bestMonthlyCost != null && approxEq(cost, bestMonthlyCost);
            return (
              <div key={modelId(model) || `idx-${index}`} className="flex items-center justify-between gap-2">
                <span className="text-sm truncate" style={{ color: seriesColor(theme, index) }}>
                  {modelDisplayName(model)}
                </span>
                {cost != null ? (
                  <span className={cn("font-mono text-sm", isBest && "font-semibold text-success")}>
                    {formatDollar(cost, t)}
                    {isBest && <WinnerMark />}
                  </span>
                ) : (
                  <span className="text-sm text-text-tertiary">{t("notAvailable")}</span>
                )}
              </div>
            );
          })}
        </div>
      </CardContent>
    </Card>
  );
});
