// src/client/features/rankings/agent-view.vue
<script setup lang="ts">
import { h } from "vue";
import { TrendingDown, TrendingUp } from "@lucide/vue";
import { useSuspenseAgentRankingsState } from "@/client/api/api-queries";
import type { AgentRankEntry } from "@/shared/types";
import RankedTableView, { modelNameCol } from "@/client/components/data/table/ranked-table-view.vue";
import PartialNotice from "@/client/components/feedback/partial-notice.vue";
import { cn } from "@/client/utils/cn";
import { orNA } from "@/client/utils/format";
import { rightCol, trendClass, type DataTableColumn } from "@/client/components/data/table/table-columns.vue";
import type { TFunction } from "@/shared/i18n";

function buildAgentColumns(t: TFunction): DataTableColumn<AgentRankEntry>[] {
  return [
    modelNameCol(
      t("model"),
      (item) => item.name,
      (item) => item.name,
    ),
    {
      id: "score",
      header: t("score"),
      align: "right",
      cell: (item) => {
        if (item.score == null || !Number.isFinite(item.score)) {
          return h("span", { class: "ui-mono-value font-semibold" }, t("notAvailable"));
        }
        const up = item.score >= 0;
        const TrendIcon = up ? TrendingUp : TrendingDown;
        const halfWidth =
          item.ciLower != null && item.ciUpper != null && Number.isFinite(item.ciLower) && Number.isFinite(item.ciUpper)
            ? (Math.abs(item.ciUpper - item.ciLower) / 2) * 100
            : null;
        return h("span", { class: "ui-mono-value inline-flex flex-col items-end leading-tight" }, [
          h("span", { class: cn("inline-flex items-center gap-1 font-semibold", trendClass(item.score, true)) }, [
            h(TrendIcon, { size: 12, "aria-hidden": "true" }),
            `${Math.abs(item.score * 100).toFixed(2)}%`,
          ]),
          halfWidth != null
            ? h("span", { class: "text-xs font-normal text-text-secondary" }, `±${halfWidth.toFixed(2)}%`)
            : null,
        ]);
      },
    },
    rightCol("creator", t("provider"), (item) => h("span", { class: "text-sm" }, item.creator), { hiddenMd: true }),
    rightCol("license", t("license"), (item) => h("span", { class: "text-sm" }, orNA(item.license, t)), {
      hiddenMd: true,
    }),
  ];
}

const getAgentRowId = (entry: AgentRankEntry) => `${entry.rank}|${entry.id}`;
const getAgentSearchFields = (entry: AgentRankEntry) => [entry.name, entry.id, entry.creator];

const state = await useSuspenseAgentRankingsState();
</script>

<template>
  <PartialNotice v-if="state.partial" />
  <RankedTableView
    :rows="state.items"
    :get-row-id="getAgentRowId"
    :get-search-fields="getAgentSearchFields"
    :build-body-columns="buildAgentColumns"
  />
</template>

// src/client/features/rankings/AgentView.tsx
"use client";
import { TrendingDown, TrendingUp } from "lucide-react";
import { useSuspenseAgentRankings } from "@/client/api/queries";
import type { AgentRankEntry } from "@/shared/types";
import { RankedTableView, modelNameCol } from "@/client/components/data/ranked";
import { cn } from "@/client/utils/cn";
import type { DataTableColumn } from "@/client/components/data/columns";
import type { useTranslation } from "@/client/providers";

function trendClass(score: number): string {
  return score >= 0 ? "text-success" : "text-destructive";
}

function buildAgentColumns(t: ReturnType<typeof useTranslation>["t"]): DataTableColumn<AgentRankEntry>[] {
  return [
    modelNameCol(
      t("model"),
      (item) => item.name,
      (item) => item.name,
    ),
    {
      id: "score",
      header: t("trend"),
      align: "right",
      // Arena reports ratios; the board shows ×100 as % with ▲/▼ and a ± band.
      cell: (item) => {
        if (item.score == null || !Number.isFinite(item.score)) {
          return <span className="ui-mono-value font-semibold">{t("notAvailable")}</span>;
        }
        const up = item.score >= 0;
        const TrendIcon = up ? TrendingUp : TrendingDown;
        const halfWidth =
          item.ciLower != null && item.ciUpper != null && Number.isFinite(item.ciLower) && Number.isFinite(item.ciUpper)
            ? ((item.ciUpper - item.ciLower) / 2) * 100
            : null;
        return (
          <span className="ui-mono-value inline-flex flex-col items-end leading-tight">
            <span className={cn("inline-flex items-center gap-1 font-semibold", trendClass(item.score))}>
              <TrendIcon size={12} aria-hidden />
              {Math.abs(item.score * 100).toFixed(2)}%
            </span>
            {halfWidth != null && (
              <span className="text-xs font-normal text-text-secondary">±{halfWidth.toFixed(2)}%</span>
            )}
          </span>
        );
      },
    },
    {
      id: "creator",
      header: t("provider"),
      align: "right",
      hiddenMd: true,
      cell: (item) => <span className="text-sm">{item.creator}</span>,
    },
    {
      id: "license",
      header: t("license"),
      align: "right",
      hiddenMd: true,
      cell: (item) => <span className="text-sm">{item.license ?? t("notAvailable")}</span>,
    },
  ];
}

const getAgentRowId = (entry: AgentRankEntry) => `${entry.rank}|${entry.id}`;
const getAgentSearchFields = (entry: AgentRankEntry) => [entry.name, entry.id, entry.creator];

export function AgentRankingsView() {
  const { data } = useSuspenseAgentRankings();
  const entries = Array.isArray((data as { entries?: unknown })?.entries)
    ? (data as { entries: AgentRankEntry[] }).entries
    : [];
  return (
    <RankedTableView
      rows={entries}
      getRowId={getAgentRowId}
      getSearchFields={getAgentSearchFields}
      buildBodyColumns={buildAgentColumns}
    />
  );
}
