// src/client/features/rankings/OpenRouterRankingsView.tsx
"use client";
import { type DataTableColumn, RightAlignedText, mobilePrimaryCol, rightCol } from "@/client/components/data/columns";
import { modelNameCol } from "@/client/components/data/ranked";
import { SearchableDataTable } from "@/client/components/data/searchable";
import { formatShortNumber, formatTrend } from "@/client/utils/format";
import { cn } from "@/client/utils/cn";
import type { OpenRouterRankEntry, OpenRouterRankingsPayload } from "@/shared/types";
import type { TranslationKey } from "@/shared/i18n";
import { ShieldAlert } from "lucide-react";
import { EmptyState } from "@/client/components/feedback";
import { OpenRouterModelDetail } from "@/client/features/models/model-details/or-detail";
import { useTranslation } from "@/client/providers";
import { useRankedColumns } from "@/client/components/data/ranked";

function trendClass(change?: number | null) {
  if (change == null || change === 0) return "text-text-tertiary";
  return change > 0 ? "text-success" : "text-destructive";
}

function tokenText(v: number | null | undefined): string {
  return typeof v === "number" && Number.isFinite(v) ? formatShortNumber(v) : "—";
}

function tokenCol(
  id: string,
  header: string,
  get: (item: OpenRouterRankEntry) => number | null | undefined,
  opts?: { primary?: boolean; muted?: boolean; hiddenMd?: boolean },
): DataTableColumn<OpenRouterRankEntry> {
  const col = opts?.primary ? mobilePrimaryCol : rightCol;
  return col(
    id,
    header,
    (item) => (
      <span className={`ui-mono-value ${opts?.muted ? "font-normal text-text-secondary" : "font-semibold"}`}>
        {tokenText(get(item))}
      </span>
    ),
    opts?.hiddenMd ? { hiddenMd: true } : undefined,
  );
}

function buildOpenRouterBodyColumns(t: (key: TranslationKey) => string): DataTableColumn<OpenRouterRankEntry>[] {
  return [
    modelNameCol(
      t("model"),
      (item) => item.name,
      (item) => item.name,
      "45%",
    ),
    tokenCol("totalTokens", t("totalTokens"), (item) => item.totalTokens, { primary: true }),
    tokenCol("inputTokens", t("inputTokens"), (item) => item.promptTokens, { hiddenMd: true }),
    tokenCol("outputTokens", t("outputTokens"), (item) => item.completionTokens, { hiddenMd: true }),
    tokenCol("requests", t("requests"), (item) => item.requestCount, { muted: true }),
    rightCol("creator", t("creator"), (item) => (
      <RightAlignedText className="ui-caption">{item.creator || t("unknown")}</RightAlignedText>
    )),
    mobilePrimaryCol("trend", t("trend"), (item) => (
      <span className={cn(trendClass(item.change), "text-xs font-mono tabular-nums inline-block")}>
        {formatTrend(item.change, t)}
      </span>
    )),
  ];
}

const getModelRowId = (r: OpenRouterRankEntry) => r.id;
const getSearchFields = (r: OpenRouterRankEntry) => [r.name, r.creator, r.id];
const renderExpandedDetail = (item: OpenRouterRankEntry) => (
  <div className="p-4 sm:p-5">
    <OpenRouterModelDetail model={item} />
  </div>
);

export function OpenRouterRankingsView({ data }: { data?: OpenRouterRankingsPayload }) {
  const { t } = useTranslation();
  const modelColumns = useRankedColumns(buildOpenRouterBodyColumns);

  if (!data) {
    return <EmptyState icon={ShieldAlert} message={t("noRankingsData")} />;
  }

  return (
    <SearchableDataTable
      data={data.tokenUsageRankings ?? []}
      columns={modelColumns}
      getRowId={getModelRowId}
      getSearchFields={getSearchFields}
      renderExpandedRow={renderExpandedDetail}
    />
  );
}

// src/client/features/rankings/openrouter-rankings-view.vue
<script setup lang="ts">
import { computed, h } from "vue";
import { ShieldAlert } from "@lucide/vue";
import RankedTableView, { modelNameCol } from "@/client/components/data/table/ranked-table-view.vue";
import {
  mobilePrimaryCol,
  monoCol,
  rightCol,
  trendClass,
  RightAlignedText,
  type DataTableColumn,
} from "@/client/components/data/table/table-columns.vue";
import EmptyState from "@/client/components/feedback/empty-state.vue";
import PartialNotice from "@/client/components/feedback/partial-notice.vue";
import OpenRouterModelDetail from "@/client/features/models/model-details/openrouter-detail.vue";
import { useTranslation } from "@/client/i18n";
import { SEARCH_FIELDS } from "@/client/search/search-fields";
import { assertPayloadShape, unwrapListPartial } from "@/client/api/payload-normalize";
import { cn } from "@/client/utils/cn";
import { formatShortNumber, formatTrend } from "@/client/utils/format";
import type { TFunction } from "@/shared/i18n";
import type { OpenRouterRankEntry, SourcePayload } from "@/shared/types";

function buildOpenRouterBodyColumns(t: TFunction): DataTableColumn<OpenRouterRankEntry>[] {
  return [
    modelNameCol(
      t("model"),
      (item) => item.name,
      (item) => item.name,
      "45%",
    ),
    monoCol("totalTokens", t("totalTokens"), (item) => formatShortNumber(item.totalTokens, t("notAvailable")), {
      mobilePrimary: true,
      emphasis: "strong",
    }),
    monoCol("inputTokens", t("inputTokens"), (item) => formatShortNumber(item.promptTokens, t("notAvailable")), {
      hiddenMd: true,
      emphasis: "strong",
    }),
    monoCol("outputTokens", t("outputTokens"), (item) => formatShortNumber(item.completionTokens, t("notAvailable")), {
      hiddenMd: true,
      emphasis: "strong",
    }),
    monoCol("requests", t("requests"), (item) => formatShortNumber(item.requestCount, t("notAvailable")), { emphasis: "muted" }),
    rightCol("creator", t("creator"), (item) =>
      h(RightAlignedText, { class: "ui-caption" }, () => item.creator || t("unknown")),
    ),
    mobilePrimaryCol("trend", t("trend"), (item) =>
      h(
        "span",
        { class: cn(trendClass(item.change), "text-xs font-mono tabular-nums inline-block") },
        formatTrend(item.change, t),
      ),
    ),
  ];
}

const getModelRowId = (r: OpenRouterRankEntry) => r.id;
const getModelRowName = (r: OpenRouterRankEntry) => r.name;

const props = defineProps<{ data?: SourcePayload<OpenRouterRankEntry[]> }>();

const { t } = useTranslation();

const state = computed(() => (props.data ? unwrapListPartial<OpenRouterRankEntry>(props.data, "openRouterRankings") : null));
assertPayloadShape(state.value?.malformed ?? false, "openRouterRankings");
</script>

<template>
  <EmptyState v-if="!state" :icon="ShieldAlert" :message="t('noRankingsData')" />
  <template v-else>
    <PartialNotice v-if="state.partial" />
    <RankedTableView
      :rows="state.data"
      :get-row-id="getModelRowId"
      :get-row-name="getModelRowName"
      :get-search-fields="SEARCH_FIELDS.or"
      :build-body-columns="buildOpenRouterBodyColumns"
    >
      <template #expandedRow="{ row }">
        <div class="p-4 sm:p-5">
          <OpenRouterModelDetail :model="row" />
        </div>
      </template>
    </RankedTableView>
  </template>
</template>
