// src/client/components/ui/sheet.vue
<script setup lang="ts">
import { nextTick, onUnmounted, ref, watch } from "vue";
import { cn } from "@/client/utils/cn";

const FOCUSABLE_SELECTOR =
  'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';

let lockCount = 0;
let prevOverflow = "";
let prevPaddingRight = "";
let inertedAppChildren: HTMLElement[] = [];

function inertAppChildren(): void {
  const root = document.getElementById("root");
  if (!root) return;
  inertedAppChildren = Array.from(root.children).filter((el): el is HTMLElement => el instanceof HTMLElement);
  for (const el of inertedAppChildren) el.setAttribute("inert", "");
}

function restoreAppChildren(): void {
  for (const el of inertedAppChildren) el.removeAttribute("inert");
  inertedAppChildren = [];
}

const props = defineProps<{ open: boolean; class?: string; ariaLabel?: string }>();
const emit = defineEmits<{ close: [] }>();

const panelRef = ref<HTMLDivElement | null>(null);
let trigger: HTMLElement | null = null;
let locked = false;

function onKeydown(event: KeyboardEvent): void {
  if (event.key === "Escape") emit("close");
  if (event.key !== "Tab") return;
  const panel = panelRef.value;
  if (!panel) return;
  const focusable = panel.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR);
  const first = focusable[0];
  const last = focusable[focusable.length - 1];
  if (!first || !last) return;
  if (event.shiftKey && document.activeElement === first) {
    event.preventDefault();
    last.focus();
  } else if (!event.shiftKey && document.activeElement === last) {
    event.preventDefault();
    first.focus();
  }
}

function lock(): void {
  const panel = panelRef.value;
  if (!panel) return;
  const active = document.activeElement;
  if (active instanceof HTMLElement && active !== document.body && !panel.contains(active)) trigger = active;
  const first = panel.querySelector<HTMLElement>(FOCUSABLE_SELECTOR);
  if (first) first.focus();
  else panel.focus();
  if (lockCount === 0) {
    prevOverflow = document.body.style.overflow;
    prevPaddingRight = document.body.style.paddingRight;
    inertAppChildren();
  }
  lockCount += 1;
  const scrollbarWidth = window.innerWidth - document.documentElement.clientWidth;
  document.body.style.overflow = "hidden";
  if (scrollbarWidth > 0) document.body.style.paddingRight = `${scrollbarWidth}px`;
  document.addEventListener("keydown", onKeydown);
  locked = true;
}

function unlock(): void {
  if (!locked) return;
  locked = false;
  document.removeEventListener("keydown", onKeydown);
  lockCount = Math.max(0, lockCount - 1);
  if (lockCount === 0) {
    document.body.style.overflow = prevOverflow;
    document.body.style.paddingRight = prevPaddingRight;
    restoreAppChildren();
  }
  if (trigger instanceof HTMLElement) trigger.focus();
  trigger = null;
}

watch(
  () => props.open,
  async (open) => {
    if (!open) {
      unlock();
      return;
    }
    await nextTick();
    lock();
  },
  { immediate: true, flush: "post" },
);

onUnmounted(unlock);
</script>

<template>
  <Teleport v-if="open" to="body">
    <div class="fixed inset-0 z-50 flex items-end justify-center sm:items-center">
      <div class="fixed inset-0 bg-black/50 animate-enter" aria-hidden="true" @click="emit('close')" />
      <div
        ref="panelRef"
        role="dialog"
        aria-modal="true"
        :aria-label="ariaLabel"
        tabindex="-1"
        :class="cn('relative z-50 w-full max-w-md ui-overlay animate-enter focus:outline-none', props.class)"
      >
        <slot />
      </div>
    </div>
  </Teleport>
</template>

// src/client/components/ui/sheet.tsx
"use client";
import { memo, useEffect, useRef } from "react";
import { cn } from "@/client/utils/cn";
import { X } from "lucide-react";
import { createPortal } from "react-dom";
import { Button } from "@/client/components/ui/button";
import { useTranslation } from "@/client/providers";

const FOCUSABLE_SELECTOR =
  'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';

let sheetLockCount = 0;
let sheetPrevOverflow = "";
let sheetPrevPaddingRight = "";

function useSheetEffects(open: boolean, onClose: () => void, panelRef: React.RefObject<HTMLDivElement | null>) {
  const onCloseRef = useRef(onClose);
  useEffect(() => {
    onCloseRef.current = onClose;
  });

  useEffect(() => {
    if (!open) return;
    const trigger = document.activeElement;
    const main = document.getElementById("main-content");
    if (sheetLockCount === 0) {
      sheetPrevOverflow = document.body.style.overflow;
      sheetPrevPaddingRight = document.body.style.paddingRight;
      main?.setAttribute("inert", "");
    }
    sheetLockCount += 1;
    const scrollbarW = window.innerWidth - document.documentElement.clientWidth;
    document.body.style.overflow = "hidden";
    if (scrollbarW > 0) document.body.style.paddingRight = `${scrollbarW}px`;

    const handler = (e: globalThis.KeyboardEvent) => {
      if (e.key === "Escape") onCloseRef.current();
      if (e.key === "Tab" && panelRef.current) {
        const focusable = panelRef.current.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR);
        const first = focusable[0];
        const last = focusable[focusable.length - 1];
        if (!first || !last) return;
        if (e.shiftKey && document.activeElement === first) {
          e.preventDefault();
          last.focus();
        } else if (!e.shiftKey && document.activeElement === last) {
          e.preventDefault();
          first.focus();
        }
      }
    };
    document.addEventListener("keydown", handler);
    const timer = setTimeout(() => {
      const panel = panelRef.current;
      if (!panel) return;
      const first = panel.querySelector<HTMLElement>(FOCUSABLE_SELECTOR);
      if (first) first.focus();
      else {
        panel.setAttribute("tabindex", "-1");
        panel.focus();
      }
    }, 50);
    return () => {
      document.removeEventListener("keydown", handler);
      clearTimeout(timer);
      sheetLockCount = Math.max(0, sheetLockCount - 1);
      if (sheetLockCount !== 0) {
        if (trigger instanceof HTMLElement) trigger.focus();
        return;
      }
      document.body.style.overflow = sheetPrevOverflow;
      document.body.style.paddingRight = sheetPrevPaddingRight;
      document.getElementById("main-content")?.removeAttribute("inert");
      if (trigger instanceof HTMLElement) trigger.focus();
    };
  }, [open, panelRef]);
}

interface SheetProps {
  open: boolean;
  onClose: () => void;
  children: React.ReactNode;
  className?: string;
  ariaLabel?: string;
}

export const Sheet = memo(function Sheet({ open, onClose, children, className, ariaLabel }: SheetProps) {
  const panelRef = useRef<HTMLDivElement>(null);
  useSheetEffects(open, onClose, panelRef);

  if (!open) return null;

  return createPortal(
    <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center" onClick={onClose}>
      <div className="fixed inset-0 bg-black/50 animate-fade-in" aria-hidden="true" />
      <div
        ref={panelRef}
        role="dialog"
        aria-modal="true"
        aria-label={ariaLabel}
        className={cn("relative z-50 w-full max-w-md ui-overlay-lg animate-sheet-up focus:outline-none", className)}
        onClick={(e) => e.stopPropagation()}
      >
        {children}
      </div>
    </div>,
    document.body,
  );
});

export const SheetHeader = memo(function SheetHeader({
  title,
  onClose,
}: {
  title: React.ReactNode;
  onClose: () => void;
}) {
  const { t } = useTranslation();
  return (
    <div className="flex items-center justify-between">
      <p className="ui-card-title">{title}</p>
      <Button variant="ghost" size="icon" onClick={onClose} aria-label={t("close")}>
        <X className="size-4" />
      </Button>
    </div>
  );
});

export const SheetBody = memo(function SheetBody({ children }: { children: React.ReactNode }) {
  return <div className="p-5 flex flex-col gap-5 max-h-[70vh] overflow-y-auto">{children}</div>;
});
