// src/client/features/news/news-view.vue
<script setup lang="ts">
import { computed, defineComponent, effectScope, onUnmounted, type PropType } from "vue";
import { Clock, ExternalLink, Search } from "@lucide/vue";
import { useTranslation } from "@/client/i18n";
import { useDevice } from "@/client/device";
import { useSuspenseNewsState } from "@/client/api/api-queries";
import { assertPayloadShape } from "@/client/api/payload-normalize";
import EmptyState from "@/client/components/feedback/empty-state.vue";
import PartialNotice from "@/client/components/feedback/partial-notice.vue";
import Pagination from "@/client/components/ui/pagination.vue";
import TabbedPage from "@/client/components/layout/tabbed-page.vue";
import SuspenseQuery from "@/client/router/suspense-query.vue";
import { useClientTab } from "@/client/hooks/use-client-tab";
import { DEFAULT_PAGE_SIZE, MOBILE_PAGE_SIZE, usePagedData } from "@/client/components/data/table";
import { formatDate, formatRelativeTime, safeHref } from "@/client/utils/format";
import type { TabItem } from "@/client/components/ui/tabs";
import type { TranslationKey } from "@/shared/i18n";
import type { NewsCategory, NewsItem } from "@/shared/types";
import { NEWS_CATEGORIES } from "@/shared/config";

const CATEGORY_LABELS: Record<NewsCategory, TranslationKey> = {
  industry: "catIndustry",
  opensource: "catOpenSource",
  hardware: "catHardware",
  funding: "catFunding",
  research: "catResearch",
};

const ROW_CLASS =
  "group flex items-start justify-between gap-4 px-4 py-3.5 transition-colors duration-fast hoverable:hover:bg-hover focus-visible:outline-none focus-visible:bg-hover";

const getNewsRowId = (item: NewsItem): string => item.link || `${item.source}::${item.title}::${item.pubDate}`;

const NewsCategoryData = defineComponent({
  props: { categoryId: { type: String as PropType<NewsCategory>, required: true } },
  async setup(loaderProps, { slots }) {
    const isMobile = useDevice();
    const scope = effectScope(true);
    onUnmounted(() => scope.stop());
    const state = await useSuspenseNewsState(loaderProps.categoryId);
    assertPayloadShape(state.value.malformed, "news");
    const paged = scope.run(() =>
      usePagedData(
        computed(() => state.value.items),
        getNewsRowId,
        () => (isMobile.value ? MOBILE_PAGE_SIZE : DEFAULT_PAGE_SIZE),
      ),
    )!;
    return () =>
      slots.default?.({
        items: paged.pagedData.value,
        page: paged.page.value,
        totalPages: paged.totalPages.value,
        goToPage: paged.goToPage,
        partial: state.value.partial,
      }) ?? null;
  },
});

const { t, lang } = useTranslation();
const [activeCategory, setActiveCategory] = useClientTab("tab", NEWS_CATEGORIES, NEWS_CATEGORIES[0]!);

const tabs = computed<TabItem[]>(() => NEWS_CATEGORIES.map((id) => ({ id, label: t(CATEGORY_LABELS[id]) })));

function rowTag(item: NewsItem): string {
  return safeHref(item.link) ? "a" : "div";
}

function rowAttrs(item: NewsItem): Record<string, string> {
  const href = safeHref(item.link);
  if (!href) return {};
  return {
    href,
    target: "_blank",
    rel: "noopener noreferrer",
    "aria-label": t("newsItemLabel", { title: item.title, source: item.source }),
  };
}
</script>

<template>
  <TabbedPage :title="t('aiNews')" :tabs="tabs" :active-tab="activeCategory" @tab-change="setActiveCategory">
    <SuspenseQuery>
      <NewsCategoryData :category-id="activeCategory">
        <template #default="{ items, page, totalPages, goToPage, partial }">
          <PartialNotice v-if="partial" />
          <EmptyState v-if="items.length === 0" :icon="Search" :message="t('noResults')" />
          <div v-else class="flex flex-col gap-2">
            <ul class="ui-card flex flex-col divide-y divide-border">
              <li v-for="item in items" :key="getNewsRowId(item)">
                <component :is="rowTag(item)" v-bind="rowAttrs(item)" :class="ROW_CLASS">
                  <h2
                    class="ui-body font-medium leading-relaxed min-w-0 break-words decoration-accent/50 underline-offset-4 group-hover:underline transition-colors duration-fast"
                  >
                    {{ item.title }}
                  </h2>
                  <div class="flex items-center gap-3 shrink-0 ui-caption mt-1">
                    <span class="hidden sm:inline truncate max-w-48">{{ item.source }}</span>
                    <span class="flex items-center gap-1.5 shrink-0" :title="formatDate(item.pubDate, lang)">
                      <Clock :size="12" aria-hidden="true" />
                      {{ formatRelativeTime(item.pubDate, t, lang) }}
                    </span>
                    <ExternalLink
                      :size="14"
                      class="md:opacity-0 md:group-hover:opacity-100 transition-opacity duration-fast shrink-0"
                      aria-hidden="true"
                    />
                  </div>
                </component>
              </li>
            </ul>
            <Pagination :page="page" :total-pages="totalPages" @change="goToPage" />
          </div>
        </template>
      </NewsCategoryData>
    </SuspenseQuery>
  </TabbedPage>
</template>

// src/client/features/news/news-view.tsx
import { useMemo } from "react";
import { ExternalLink, Clock, Search } from "lucide-react";
import { useDevice, useTranslation } from "@/client/providers";
import type { TranslationKey } from "@/shared/i18n";
import { Pagination } from "@/client/components/ui/pagination";
import { useSuspenseNewsState } from "@/client/api/api-queries";
import { assertPayloadShape } from "@/client/api/payload-normalize";
import { EmptyState, PartialNotice } from "@/client/components/feedback";
import { SuspenseQuery } from "@/client/router/suspense-query";
import { safeHref, formatRelativeTime, formatDate } from "@/client/utils/format";
import { TabbedPage } from "@/client/components/layout";
import { useClientTab } from "@/client/hooks/use-client-tab";
import { type TabItem } from "@/client/components/ui/tabs";
import type { NewsItem, NewsCategory } from "@/shared/types";
import { NEWS_CATEGORIES } from "@/shared/config";
import { usePagedData } from "@/client/components/data/table";

const CATEGORY_LABELS: Record<NewsCategory, TranslationKey> = {
  industry: "catIndustry",
  opensource: "catOpenSource",
  hardware: "catHardware",
  funding: "catFunding",
  research: "catResearch",
};

const getNewsRowId = (item: NewsItem): string => item.link || `${item.source}::${item.title}::${item.pubDate}`;

function NewsList({ news }: { news: NewsItem[] }) {
  const { t, lang } = useTranslation();
  const { isMobile } = useDevice();
  const { page, totalPages, pagedData: currentNews, goToPage } = usePagedData(news, getNewsRowId, isMobile ? 10 : 20);

  const items = useMemo(
    () =>
      currentNews.map((item) => ({
        item,
        dateLabel: formatDate(item.pubDate, lang),
        relativeLabel: formatRelativeTime(item.pubDate, t, lang),
      })),
    [currentNews, lang, t],
  );

  if (news.length === 0) return <EmptyState icon={Search} message={t("noResults")} />;

  return (
    <div className="flex flex-col gap-2">
      {}
      <ul className="ui-card flex flex-col divide-y divide-border animate-fade-in">
        {items.map(({ item, dateLabel, relativeLabel }) => {
          const href = safeHref(item.link);
          const key = getNewsRowId(item);
          const body = (
            <>
              <h2 className="ui-body font-medium leading-relaxed min-w-0 break-words decoration-accent/50 underline-offset-4 group-hover:underline transition-colors duration-fast">
                {item.title}
              </h2>
              <div className="flex items-center gap-3 shrink-0 ui-caption mt-1">
                <span className="hidden sm:inline truncate max-w-48">{item.source}</span>
                <span className="flex items-center gap-1.5 shrink-0" title={dateLabel}>
                  <Clock size={12} aria-hidden="true" />
                  {relativeLabel}
                </span>
                <ExternalLink
                  size={14}
                  className="md:opacity-0 md:group-hover:opacity-100 transition-opacity duration-fast shrink-0"
                  aria-hidden="true"
                />
              </div>
            </>
          );
          const rowClass =
            "group flex items-start justify-between gap-4 px-4 py-3.5 transition-colors duration-fast hoverable:hover:bg-hover focus-visible:outline-none focus-visible:bg-hover";
          return (
            <li key={key}>
              {href ? (
                <a
                  href={href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className={rowClass}
                  aria-label={t("newsItemLabel", { title: item.title, source: item.source })}
                >
                  {body}
                </a>
              ) : (
                <div className={rowClass}>{body}</div>
              )}
            </li>
          );
        })}
      </ul>
      {totalPages > 1 && <Pagination page={page} totalPages={totalPages} onChange={goToPage} />}
    </div>
  );
}

function NewsCategoryContent({ categoryId }: { categoryId: NewsCategory }) {
  const { items: news, partial, malformed } = useSuspenseNewsState(categoryId);
  assertPayloadShape(malformed, "news");
  return (
    <>
      {partial && <PartialNotice />}
      <NewsList key={categoryId} news={news} />
    </>
  );
}

export function NewsView() {
  const { t } = useTranslation();
  const [activeCategory, setActiveCategory] = useClientTab("tab", NEWS_CATEGORIES, NEWS_CATEGORIES[0]!);

  const tabs: TabItem[] = useMemo(() => NEWS_CATEGORIES.map((id) => ({ id, label: t(CATEGORY_LABELS[id]) })), [t]);

  return (
    <TabbedPage title={t("aiNews")} tabs={tabs} activeTab={activeCategory} onTabChange={setActiveCategory}>
      <SuspenseQuery resetKey={activeCategory}>
        <NewsCategoryContent categoryId={activeCategory} />
      </SuspenseQuery>
    </TabbedPage>
  );
}
