// src/client/features/compare/compare-tray.vue
<script setup lang="ts">
import { computed, getCurrentInstance, watch } from "vue";
import { ArrowLeftRight, Trash2, X } from "@lucide/vue";
import Button from "@/client/components/ui/button.vue";
import Badge from "@/client/components/ui/badge.vue";
import { useTranslation } from "@/client/i18n";
import { useCompareStore } from "@/client/stores";
import { modelDisplayName } from "@/client/utils/model-utils";
import type { ArtificialAnalysisModel } from "@/shared/types";
import { modelKeyOf } from "./compare-logic";

const LIMIT_NOTICE_MS = 2500;

const props = defineProps<{ models: ArtificialAnalysisModel[] }>();

const emit = defineEmits<{
  remove: [model: ArtificialAnalysisModel];
  clear: [];
  compare: [];
}>();

const { t } = useTranslation();
const store = useCompareStore();

const hasCompare = getCurrentInstance()?.vnode.props?.onCompare != null;
const showLimit = computed(() => store.exceedAt != null);
const canCompare = computed(() => props.models.length >= 2);

watch(
  () => store.exceedAt,
  (exceedAt, _previous, onCleanup) => {
    if (exceedAt == null) return;
    const timer = setTimeout(() => store.clearExceed(), LIMIT_NOTICE_MS);
    onCleanup(() => clearTimeout(timer));
  },
  { immediate: true },
);
</script>

<template>
  <div class="ui-card flex flex-wrap gap-3 items-center justify-between px-3 py-2.5">
    <div class="flex flex-wrap gap-2 items-center min-w-0">
      <slot name="leading" />
      <Badge
        v-for="(model, index) in models"
        :key="modelKeyOf(model, index)"
        class="pl-3 pr-1 py-1 text-sm normal-case tracking-normal text-text-primary hoverable:hover:border-text-tertiary/40"
      >
        <span class="font-medium truncate max-w-36">{{ modelDisplayName(model) }}</span>
        <button
          type="button"
          :aria-label="t('removeModel', { name: modelDisplayName(model) })"
          class="shrink-0 p-1 text-text-secondary hoverable:hover:text-text-primary hoverable:hover:bg-hover transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30"
          @click="emit('remove', model)"
        >
          <X :size="14" />
        </button>
      </Badge>
    </div>
    <div class="flex gap-2 w-full sm:w-auto">
      <Button size="sm" variant="outline" class="flex-1 sm:flex-none" @click="emit('clear')">
        <Trash2 :size="14" /> {{ t("clear") }}
      </Button>
      <Button
        v-if="hasCompare"
        size="sm"
        :variant="canCompare ? 'primary' : 'outline'"
        :disabled="!canCompare"
        class="flex-1 sm:flex-none"
        @click="emit('compare')"
      >
        <ArrowLeftRight :size="14" /> {{ t("compareSelected") }}
      </Button>
    </div>
    <p v-if="hasCompare && !canCompare && models.length > 0" class="ui-caption w-full">{{ t("compareLimit") }}</p>
    <p v-if="showLimit" class="ui-caption text-warning w-full animate-enter" role="alert">
      {{ t("compareLimitTwo") }}
    </p>
  </div>
</template>

// src/client/features/compare/compare-tray.tsx
import { memo, useEffect, type ReactNode } from "react";
import { ArrowLeftRight, Trash2, X } from "lucide-react";
import { Button } from "@/client/components/ui/button";
import { Badge } from "@/client/components/ui/primitives";
import { useTranslation } from "@/client/providers";
import { useCompareStore } from "@/client/stores";
import { modelDisplayName, modelId } from "@/client/utils/model-utils";
import type { ArtificialAnalysisModel } from "@/shared/types";

const CompareChip = memo(function CompareChip({
  model,
  onRemove,
}: {
  model: ArtificialAnalysisModel;
  onRemove: (m: ArtificialAnalysisModel) => void;
}) {
  const { t } = useTranslation();
  const name = modelDisplayName(model);
  return (
    <Badge className="pl-3 pr-1 py-1 text-sm normal-case tracking-normal text-text-primary hoverable:hover:border-text-tertiary/40">
      <span className="font-medium truncate max-w-36">{name}</span>
      <button
        type="button"
        onClick={() => onRemove(model)}
        aria-label={t("removeModel", { name })}
        className="shrink-0 p-1 text-text-secondary hoverable:hover:text-text-primary hoverable:hover:bg-hover transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30"
      >
        <X size={14} />
      </button>
    </Badge>
  );
});

export const CompareChipBar = memo(function CompareChipBar({
  models,
  onRemove,
  onClear,
  onCompare,
  leading,
}: {
  models: ArtificialAnalysisModel[];
  onRemove: (model: ArtificialAnalysisModel) => void;
  onClear: () => void;
  onCompare?: () => void;
  leading?: ReactNode;
}) {
  const { t } = useTranslation();
  const lastExceedAt = useCompareStore((s) => s.lastExceedAt);
  const clearExceed = useCompareStore((s) => s.clearExceed);
  const showLimit = lastExceedAt !== null;
  useEffect(() => {
    if (lastExceedAt == null) return;
    const timer = setTimeout(() => clearExceed(), 2500);
    return () => clearTimeout(timer);
  }, [lastExceedAt, clearExceed]);
  const canCompare = models.length >= 2;
  return (
    <div className="ui-card flex flex-wrap gap-3 items-center justify-between px-3 py-2.5">
      <div className="flex flex-wrap gap-2 items-center min-w-0">
        {leading}
        {models.map((model, index) => (
          <CompareChip key={modelId(model) || `idx-${index}`} model={model} onRemove={onRemove} />
        ))}
      </div>
      <div className="flex gap-2 w-full sm:w-auto">
        <Button size="sm" variant="outline" onClick={onClear} className="flex-1 sm:flex-none">
          <Trash2 size={14} /> {t("clear")}
        </Button>
        {onCompare && (
          <Button
            size="sm"
            variant={canCompare ? "primary" : "outline"}
            onClick={onCompare}
            disabled={!canCompare}
            className="flex-1 sm:flex-none"
          >
            <ArrowLeftRight size={14} /> {t("compareSelected")}
          </Button>
        )}
      </div>
      {onCompare && !canCompare && models.length > 0 && <p className="ui-caption w-full">{t("compareLimit")}</p>}
      {showLimit && (
        <p className="ui-caption text-warning w-full animate-fade-in" role="alert">
          {t("compareLimitTwo")}
        </p>
      )}
    </div>
  );
});
