// src/client/features/compare/compare-layout.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "@/client/router";
import { CenteredPageState, EmptyState } from "@/client/components/feedback";
import { CompareChipBar } from "./compare-tray";
import { useTranslation } from "@/client/providers";
import { useCompareModels, useCompareStore, usePruneCompareIds } from "@/client/stores";
import { useSuspenseArtificialRankings } from "@/client/api/api-queries";
import type { ArtificialAnalysisModel } from "@/shared/types";
import { BackButton, DetailPageLayout, PageContainer } from "@/client/components/layout";
import { SuspenseQuery } from "@/client/router/suspense-query";
import { modelId } from "@/client/utils/model-utils";

const PRUNE_NOTICE_MS = 8000;

interface ComparePageLayoutProps {
  backTo: string;
  title: string;
  children: (models: ArtificialAnalysisModel[]) => React.ReactNode;
}

function CompareLayoutContent({ backTo, title, children }: ComparePageLayoutProps) {
  const router = useRouter();
  const { t } = useTranslation();
  const removeCompareModel = useCompareStore((s) => s.removeCompareModel);
  const clearCompare = useCompareStore((s) => s.clearCompare);
  const compareIds = useCompareStore((s) => s.compareIds);
  const rankings = useSuspenseArtificialRankings();
  const models = useCompareModels(rankings);
  usePruneCompareIds(rankings);
  const modelIds = useMemo(() => new Set(models.map(modelId).filter(Boolean)), [models]);
  const hasStaleId = modelIds.size > 0 && compareIds.some((id) => !modelIds.has(id));
  const [pruned, setPruned] = useState(false);
  useEffect(() => {
    if (!hasStaleId) return;
    const timer = setTimeout(() => setPruned(true), 0);
    return () => clearTimeout(timer);
  }, [hasStaleId]);
  useEffect(() => {
    if (!pruned) return;
    const hide = setTimeout(() => setPruned(false), PRUNE_NOTICE_MS);
    return () => clearTimeout(hide);
  }, [pruned]);
  const handleClearAndBack = useCallback(() => {
    clearCompare();
    router.replace(backTo);
  }, [clearCompare, router, backTo]);

  if (models.length < 2) {
    return (
      <CenteredPageState>
        <div className="w-full">
          <CompareChipBar models={models} onRemove={removeCompareModel} onClear={handleClearAndBack} />
        </div>
        <EmptyState message={t("compareLimit")} compact />
        {pruned && (
          <p className="ui-caption" role="status">
            {t("compareStale")}
          </p>
        )}
        <BackButton labelKey="back" to={backTo} />
      </CenteredPageState>
    );
  }

  return (
    <PageContainer>
      <DetailPageLayout backLabelKey="back" backTo={backTo} title={title} description={t("artificialSource")} compact>
        <CompareChipBar models={models} onRemove={removeCompareModel} onClear={handleClearAndBack} />
        {children(models)}
      </DetailPageLayout>
    </PageContainer>
  );
}

export function ComparePageLayout(props: ComparePageLayoutProps) {
  return (
    <SuspenseQuery>
      <CompareLayoutContent {...props} />
    </SuspenseQuery>
  );
}

// src/client/features/compare/compare-layout.vue
<script setup lang="ts">
import { computed, defineComponent, effectScope, onUnmounted, ref, watch } from "vue";
import { useRouter } from "vue-router";
import { useTranslation } from "@/client/i18n";
import EmptyState from "@/client/components/feedback/empty-state.vue";
import BackButton from "@/client/components/layout/back-button.vue";
import DetailPageLayout from "@/client/components/layout/detail-page-layout.vue";
import PageContainer from "@/client/components/layout/page-container.vue";
import SuspenseQuery from "@/client/router/suspense-query.vue";
import { useSuspenseArtificialRankings } from "@/client/api/api-queries";
import { useCompareModels, useCompareStore, usePruneCompareIds } from "@/client/stores";
import { modelId } from "@/client/utils/model-utils";
import CompareChipBar from "./compare-tray.vue";

const PRUNE_NOTICE_MS = 8000;

const props = defineProps<{ backTo: string; title: string }>();

const store = useCompareStore();
const { t } = useTranslation();

const CompareModels = defineComponent({
  props: { backTo: { type: String, required: true }, title: { type: String, required: true } },
  async setup(loaderProps, { slots }) {
    const router = useRouter();
    const loaderStore = useCompareStore();
    const scope = effectScope(true);
    onUnmounted(() => scope.stop());
    const rankings = await useSuspenseArtificialRankings();
    const vm = scope.run(() => {
      const models = useCompareModels(rankings);
      usePruneCompareIds(rankings);
      const modelIds = computed(() => new Set(models.value.map(modelId).filter(Boolean)));
      const hasStaleId = computed(
        () => modelIds.value.size > 0 && loaderStore.compareIds.some((id) => !modelIds.value.has(id)),
      );
      const pruned = ref(false);
      watch(
        hasStaleId,
        (stale, _previous, onCleanup) => {
          if (!stale) return;
          pruned.value = true;
          const hide = setTimeout(() => {
            pruned.value = false;
          }, PRUNE_NOTICE_MS);
          onCleanup(() => clearTimeout(hide));
        },
        { immediate: true },
      );
      return { models, pruned };
    })!;
    function clearAndBack(): void {
      loaderStore.clearCompare();
      void router.replace(loaderProps.backTo);
    }
    return () =>
      slots.default?.({
        models: vm.models.value,
        pruned: vm.pruned.value,
        clearAndBack,
      }) ?? null;
  },
});
</script>

<template>
  <PageContainer>
    <SuspenseQuery>
      <CompareModels :back-to="props.backTo" :title="props.title">
        <template #default="{ models, pruned, clearAndBack }">
          <div v-if="models.length < 2" class="flex flex-col gap-3 items-center py-16 text-center animate-enter">
            <div class="w-full">
              <CompareChipBar :models="models" @remove="store.removeCompareModel" @clear="clearAndBack" />
            </div>
            <EmptyState :message="t('compareLimit')" compact />
            <p v-if="pruned" class="ui-caption" role="status">
              {{ t("compareStale") }}
            </p>
            <BackButton label-key="back" :to="props.backTo" />
          </div>
          <DetailPageLayout
            v-else
            back-label-key="back"
            :back-to="props.backTo"
            :title="props.title"
            :description="t('artificialSource')"
            compact
          >
            <CompareChipBar :models="models" @remove="store.removeCompareModel" @clear="clearAndBack" />
            <slot :models="models" />
          </DetailPageLayout>
        </template>
      </CompareModels>
    </SuspenseQuery>
  </PageContainer>
</template>
