// src/client/features/compare/compare-radar-chart.vue
<script lang="ts">
import { registerRadar } from "@/client/utils/charts-register";

registerRadar();
</script>

<script setup lang="ts">
import { computed } from "vue";
import type { ChartData, ChartOptions } from "chart.js";
import { useTranslation } from "@/client/i18n";
import { hexToRgba, legendStyle, seriesColor, useChartTheme } from "@/client/theme/chart-theme";
import Card from "@/client/components/ui/card.vue";
import CardContent from "@/client/components/ui/card-content.vue";
import ChartCanvas from "@/client/components/ui/chart-canvas.vue";
import ChartFrame from "@/client/components/ui/chart-frame.vue";
import { axisTickStyle, chartBase, defaultTooltipOptions } from "@/client/utils/charts";
import type { ArtificialAnalysisModel } from "@/shared/types";
import { modelDisplayName, modelId } from "@/client/utils/model-utils";
import { buildRadarData, radarMaxFor } from "./compare-logic";

const props = defineProps<{ models: ArtificialAnalysisModel[] }>();

const { t } = useTranslation();
const theme = useChartTheme();

const radarData = computed(() => buildRadarData(t, props.models));
const radarMax = computed(() => radarMaxFor(radarData.value));

const data = computed<ChartData<"radar">>(() => ({
  labels: radarData.value.map((row) => row.metric),
  datasets: props.models.map((model, index) => {
    const color = seriesColor(theme.value, index);
    const key = modelId(model);
    return {
      label: modelDisplayName(model),
      data: radarData.value.map((row) => (key ? (row.values[key] ?? null) : null)),
      borderColor: color,
      backgroundColor: hexToRgba(color, 0.06),
      borderWidth: 2,
      pointRadius: 2,
      pointHoverRadius: 4,
    };
  }),
}));

const options = computed<ChartOptions<"radar">>(() => ({
  ...chartBase,
  interaction: { mode: "index", intersect: false },
  layout: { padding: 8 },
  scales: {
    r: {
      min: 0,
      max: radarMax.value,
      ticks: {
        ...axisTickStyle(theme.value),
        stepSize: 25,
        backdropColor: "transparent",
      },
      grid: { color: theme.value.grid },
      angleLines: { color: theme.value.grid },
      pointLabels: { color: theme.value.tickSecondary, font: { size: 11 } },
    },
  },
  plugins: {
    legend: legendStyle(theme.value),
    tooltip: defaultTooltipOptions(theme.value),
  },
}));

const caption = computed(() =>
  radarData.value
    .map((row) => {
      const values = props.models.map((m) => {
        const key = modelId(m);
        const v = key ? row.values[key] : null;
        return `${modelDisplayName(m)}: ${typeof v === "number" ? v.toFixed(1) : "—"}`;
      });
      return `${row.metric} — ${values.join(", ")}`;
    })
    .join(""),
);
</script>

<template>
  <Card class="w-full md:w-1/2">
    <CardContent class="h-full flex items-center justify-center">
      <ChartFrame height="h-[240px] sm:h-[320px]">
        <ChartCanvas type="radar" :data="data" :options="options" role="img" :aria-label="t('modelComparison')" />
        <figcaption class="sr-only">{{ caption }}</figcaption>
      </ChartFrame>
    </CardContent>
  </Card>
</template>

// src/client/features/compare/compare-radar-chart.tsx
import { useMemo } from "react";
import type { ChartOptions } from "chart.js";
import { Radar } from "react-chartjs-2";
import { registerRadar } from "@/client/utils/charts-register";

registerRadar();
import { useTranslation } from "@/client/providers";
import { useChartTheme, hexToRgba, legendStyle, seriesColor } from "@/client/theme/chart-theme";
import { Card, CardContent } from "@/client/components/ui/card";
import { ChartFrame } from "@/client/components/ui/chart-frame";
import { axisTickStyle, chartBase, defaultTooltipOptions } from "@/client/utils/charts";
import type { ArtificialAnalysisModel } from "@/shared/types";
import { modelDisplayName, modelId } from "@/client/utils/model-utils";
import { buildRadarData, radarMaxFor } from "./compare-logic";

export function CompareRadarChart({ models }: { models: ArtificialAnalysisModel[] }) {
  const { t } = useTranslation();
  const theme = useChartTheme();
  const radarData = useMemo(() => buildRadarData(t, models), [models, t]);
  const radarMax = useMemo(() => radarMaxFor(radarData), [radarData]);

  const data = useMemo(
    () => ({
      labels: radarData.map((row) => row.metric),
      datasets: models.map((model, index) => {
        const color = seriesColor(theme, index);
        const key = modelId(model);
        return {
          label: modelDisplayName(model),
          data: radarData.map((row) => (key ? (row.values[key] ?? null) : null)),
          borderColor: color,
          backgroundColor: hexToRgba(color, 0.06),
          borderWidth: 2,
          pointRadius: 2,
          pointHoverRadius: 4,
        };
      }),
    }),
    [radarData, models, theme],
  );

  const options = useMemo<ChartOptions<"radar">>(
    () => ({
      ...chartBase,
      interaction: { mode: "index", intersect: false },
      layout: { padding: 8 },
      scales: {
        r: {
          min: 0,
          max: radarMax,
          ticks: {
            ...axisTickStyle(theme),
            stepSize: 25,
            backdropColor: "transparent",
          },
          grid: { color: theme.grid },
          angleLines: { color: theme.grid },
          pointLabels: { color: theme.tickSecondary, font: { size: 11 } },
        },
      },
      plugins: {
        legend: legendStyle(theme),
        tooltip: defaultTooltipOptions(theme),
      },
    }),
    [theme, radarMax],
  );

  return (
    <Card className="w-full md:w-1/2">
      <CardContent className="h-full flex items-center justify-center">
        <ChartFrame height="h-[240px] sm:h-[320px]">
          <Radar data={data} options={options} role="img" aria-label={t("modelComparison")} />
          <figcaption className="sr-only">
            {radarData.map((row) => {
              const values = models.map((m) => {
                const key = modelId(m);
                const v = key ? row.values[key] : null;
                return `${modelDisplayName(m)}: ${typeof v === "number" ? v.toFixed(1) : "—"}`;
              });
              return `${row.metric} — ${values.join(", ")}`;
            })}
          </figcaption>
        </ChartFrame>
      </CardContent>
    </Card>
  );
}
