// src/client/features/compare/CompareTable.tsx
"use client";
import { memo, useCallback, useMemo, type ReactNode } from "react";
import { TrendingDown, TrendingUp } from "lucide-react";
import { useTranslation, useDevice } from "@/client/providers";
import { useChartTheme, seriesColor } from "@/client/theme/chart-theme";
import { Card, CardContent } from "@/client/components/ui/card";
import { Dot } from "@/client/components/ui/primitives";
import { cn } from "@/client/utils/cn";
import { modelId } from "@/client/utils/model";
import { computeWinners, rowKey, type CompareRow, type Winner } from "./logic";
import type { ArtificialAnalysisModel } from "@/shared/types";

interface ThProps {
  align?: "left" | "right";
  className?: string;
  style?: React.CSSProperties;
  children?: ReactNode;
  scope?: "col" | "row";
}

const Th = memo(function Th({ align = "left", className, style, children, scope }: ThProps) {
  return (
    <th
      scope={scope}
      className={cn(
        "px-4 py-2.5 text-xs font-medium text-text-tertiary",
        align === "right" ? "text-right" : "text-left",
        className,
      )}
      style={style}
    >
      {children}
    </th>
  );
});

interface TdProps {
  align?: "left" | "right";
  mono?: boolean;
  className?: string;
  style?: React.CSSProperties;
  children?: ReactNode;
}

const Td = memo(function Td({ align = "left", mono, className, style, children }: TdProps) {
  return (
    <td
      className={cn(
        "px-4 py-2.5 text-sm",
        mono && "font-mono tabular-nums",
        align === "right" && "text-right",
        className,
      )}
      style={style}
    >
      {children}
    </td>
  );
});

const Tr = memo(function Tr({ className, children, ...props }: React.HTMLAttributes<HTMLTableRowElement>) {
  return (
    <tr className={cn("border-b border-border last:border-b-0", className)} {...props}>
      {children}
    </tr>
  );
});

interface CompareTableProps {
  rows: CompareRow<ArtificialAnalysisModel>[];
  models: ArtificialAnalysisModel[];
  renderValue: (
    row: CompareRow<ArtificialAnalysisModel>,
    model: ArtificialAnalysisModel,
    winner: Winner | null,
  ) => ReactNode;
  mobileLayout?: "metric-rows" | "model-cards";
}

interface TablePartsProps extends Omit<CompareTableProps, "mobileLayout"> {
  winners: Map<string, Map<string, Winner>>;
  getKey: (m: ArtificialAnalysisModel, index: number) => string;
  getName: (m: ArtificialAnalysisModel) => string;
  getColor: (index: number) => string;
}

const modelKeyOf = (m: ArtificialAnalysisModel, index: number) => modelId(m) || `idx-${index}`;
const modelNameOf = (m: ArtificialAnalysisModel) => m.short_name || m.name;

function useModelColorOf(): (index: number) => string {
  const theme = useChartTheme();
  return useCallback((index: number) => seriesColor(theme, index), [theme]);
}

export const WinnerMark = memo(function WinnerMark() {
  return <TrendingUp size={12} className="inline ml-0.5 text-success" aria-hidden="true" />;
});

/** Shared value cell: applies the win/loss styling and marks in one place. */
export const WinnerValue = memo(function WinnerValue({ value, winner }: { value: string; winner: Winner | null }) {
  return (
    <span
      className={cn(
        "font-mono tabular-nums",
        winner === "win" && "font-semibold text-success",
        winner === "loss" && "text-destructive",
      )}
    >
      {value}
      {winner === "win" && <WinnerMark />}
      {winner === "loss" && <TrendingDown size={12} className="inline ml-0.5 text-destructive" aria-hidden="true" />}
    </span>
  );
});

function DesktopTable({ rows, models, getKey, getName, getColor, renderValue, winners }: TablePartsProps) {
  const { t } = useTranslation();
  return (
    <Card>
      <CardContent>
        <div className="min-w-0 w-full overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border">
                <Th className="font-semibold text-text-secondary sticky left-0 z-10 bg-bg-card">{t("metric")}</Th>
                {models.map((model, index) => (
                  <Th
                    key={getKey(model, index)}
                    align="right"
                    className="font-semibold"
                    style={{ color: getColor(index) }}
                  >
                    {getName(model)}
                  </Th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.map((row) => (
                <Tr key={rowKey(row)} className="hover:bg-hover transition-colors">
                  <Th scope="row" className="text-text-secondary sticky left-0 bg-bg-card z-10">
                    {row.label}
                  </Th>
                  {models.map((model, index) => (
                    <Td key={getKey(model, index)} align="right">
                      {renderValue(row, model, winners.get(rowKey(row))?.get(getKey(model, index)) ?? null)}
                    </Td>
                  ))}
                </Tr>
              ))}
            </tbody>
          </table>
        </div>
      </CardContent>
    </Card>
  );
}

function MobileTable({
  rows,
  models,
  getKey,
  getName,
  getColor,
  renderValue,
  winners,
  layout,
}: TablePartsProps & { layout: "metric-rows" | "model-cards" }) {
  if (layout === "model-cards") {
    return (
      <div className="flex flex-col gap-3">
        {models.map((model, index) => (
          <Card key={getKey(model, index)}>
            <CardContent className="flex flex-col gap-3 sm:p-4">
              <p className="flex items-center gap-2 text-sm font-medium truncate" style={{ color: getColor(index) }}>
                <Dot size="sm" color={getColor(index)} />
                {getName(model)}
              </p>
              <div className="flex flex-col gap-2">
                {rows.map((row) => (
                  <div key={rowKey(row)} className="flex items-center justify-between gap-3">
                    <span className="ui-caption">{row.label}</span>
                    {renderValue(row, model, winners.get(rowKey(row))?.get(getKey(model, index)) ?? null)}
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    );
  }

  return (
    <Card>
      <CardContent className="sm:p-4">
        <div className="flex flex-col divide-y divide-border">
          {rows.map((row) => {
            const perModel = winners.get(rowKey(row));
            return (
              <div key={rowKey(row)} className="flex items-center justify-between gap-3 py-3 first:pt-0 last:pb-0">
                <span className="text-xs font-medium text-text-secondary shrink-0">{row.label}</span>
                <div className="flex flex-wrap items-center justify-end gap-x-3 gap-y-1">
                  {models.map((model, index) => (
                    <span key={getKey(model, index)} className="flex items-center gap-1">
                      <Dot size="sm" color={getColor(index)} />
                      {renderValue(row, model, perModel?.get(getKey(model, index)) ?? null)}
                    </span>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </CardContent>
    </Card>
  );
}

function CompareTableInner({ rows, models, renderValue, mobileLayout = "metric-rows" }: CompareTableProps) {
  const { isMobile } = useDevice();
  const getColor = useModelColorOf();
  const winners = useMemo(() => computeWinners(rows, models, modelKeyOf), [rows, models]);

  const parts = useMemo(
    () => ({ rows, models, getKey: modelKeyOf, getName: modelNameOf, getColor, renderValue, winners }),
    [rows, models, getColor, renderValue, winners],
  );
  if (isMobile) {
    return <MobileTable {...parts} layout={mobileLayout} />;
  }

  return <DesktopTable {...parts} />;
}

export const CompareTable = memo(CompareTableInner) as typeof CompareTableInner;

// src/client/features/compare/compare-table.vue
<script lang="ts">
import { h, type FunctionalComponent } from "vue";
import { TrendingDown, TrendingUp } from "@lucide/vue";
import { cn } from "@/client/utils/cn";
import type { Winner } from "./compare-logic";

export const WinnerMark: FunctionalComponent = () =>
  h(TrendingUp, { size: 12, class: "inline ml-0.5 text-success", "aria-hidden": "true" });

export const WinnerValue: FunctionalComponent<{ value: string; winner: Winner | null }> = (props) =>
  h(
    "span",
    {
      class: cn(
        "font-mono tabular-nums",
        props.winner === "win" && "font-semibold text-success",
        props.winner === "loss" && "text-destructive",
      ),
    },
    [
      props.value,
      props.winner === "win" ? h(WinnerMark) : null,
      props.winner === "loss"
        ? h(TrendingDown, { size: 12, class: "inline ml-0.5 text-destructive", "aria-hidden": "true" })
        : null,
    ],
  );
</script>

<script setup lang="ts">
import { computed, type VNodeChild } from "vue";
import { useTranslation } from "@/client/i18n";
import { useDevice } from "@/client/device";
import { seriesColor, useChartTheme } from "@/client/theme/chart-theme";
import Card from "@/client/components/ui/card.vue";
import CardContent from "@/client/components/ui/card-content.vue";
import Dot from "@/client/components/ui/dot.vue";
import { modelDisplayName } from "@/shared/utils/models";
import type { ArtificialAnalysisModel } from "@/shared/types";
import { computeWinners, modelKeyOf, rowKey, type CompareRow } from "./compare-logic";

const props = defineProps<{
  rows: CompareRow<ArtificialAnalysisModel>[];
  models: ArtificialAnalysisModel[];
  renderValue: (
    row: CompareRow<ArtificialAnalysisModel>,
    model: ArtificialAnalysisModel,
    winner: Winner | null,
  ) => VNodeChild;
}>();

const { t } = useTranslation();
const theme = useChartTheme();
const isMobile = useDevice();

const winners = computed(() => computeWinners(props.rows, props.models, modelKeyOf));

const ValueView = (cellProps: { render: () => VNodeChild }): VNodeChild => cellProps.render();

function getWinner(
  row: CompareRow<ArtificialAnalysisModel>,
  model: ArtificialAnalysisModel,
  index: number,
): Winner | null {
  return winners.value.get(rowKey(row))?.get(modelKeyOf(model, index)) ?? null;
}
</script>

<template>
  <div v-if="isMobile" class="flex flex-col gap-3">
    <Card v-for="(model, index) in models" :key="modelKeyOf(model, index)">
      <CardContent class="flex flex-col gap-3 sm:p-4">
        <p class="flex items-center gap-2 text-sm font-medium truncate" :style="{ color: seriesColor(theme, index) }">
          <Dot size="sm" :color="seriesColor(theme, index)" />
          {{ modelDisplayName(model) }}
        </p>
        <div class="flex flex-col gap-2">
          <div v-for="row in rows" :key="rowKey(row)" class="flex items-center justify-between gap-3">
            <span class="ui-caption">{{ row.label }}</span>
            <ValueView :render="() => renderValue(row, model, getWinner(row, model, index))" />
          </div>
        </div>
      </CardContent>
    </Card>
  </div>
  <Card v-else>
    <CardContent>
      <div class="min-w-0 w-full overflow-x-auto">
        <table class="w-full text-sm">
          <thead>
            <tr class="border-b border-border">
              <th
                scope="col"
                :class="
                  cn(
                    'px-4 py-3.5 text-xs font-medium text-text-tertiary',
                    'text-left',
                    'font-semibold text-text-secondary sticky left-0 z-10 bg-bg-card',
                  )
                "
              >
                {{ t("metric") }}
              </th>
              <th
                v-for="(model, index) in models"
                :key="modelKeyOf(model, index)"
                scope="col"
                :class="cn('px-4 py-3.5 text-xs font-medium text-text-tertiary', 'text-right', 'font-semibold')"
                :style="{ color: seriesColor(theme, index) }"
              >
                {{ modelDisplayName(model) }}
              </th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in rows" :key="rowKey(row)" class="border-b border-border last:border-b-0">
              <th
                scope="row"
                :class="
                  cn(
                    'px-4 py-3.5 text-xs font-medium text-text-tertiary',
                    'text-left',
                    'text-text-secondary sticky left-0 bg-bg-card z-10',
                  )
                "
              >
                {{ row.label }}
              </th>
              <td
                v-for="(model, index) in models"
                :key="modelKeyOf(model, index)"
                :class="cn('px-4 py-3.5 text-sm', 'text-right')"
              >
                <ValueView :render="() => renderValue(row, model, getWinner(row, model, index))" />
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </CardContent>
  </Card>
</template>
