// src/client/features/compare/price-compare-view.tsx
import { Suspense, memo, useCallback, useMemo, type ReactNode } from "react";
import { useTranslation } from "@/client/providers";
import type { ArtificialAnalysisModel } from "@/shared/types";
import { formatDollar } from "@/client/utils/format";
import { ChartCard } from "@/client/components/ui/chart-frame";
import { buildPriceRows, type CompareRow, type Winner } from "./compare-logic";
import { CompareTable, WinnerValue } from "@/client/features/compare/compare-table";
import { CostEstimator } from "@/client/features/compare/price-compare/estimator";
import { MODEL_SOURCES } from "@/client/config/nav-config";
import { ComparePageLayout } from "./compare-layout";
import { loadableView } from "@/client/router/lazy-view";

const PriceChart = loadableView(() =>
  import("@/client/features/compare/price-compare/price-chart").then((m) => ({ default: m.PriceChart })),
);

const PriceCompareContent = memo(function PriceCompareContent({ models }: { models: ArtificialAnalysisModel[] }) {
  const { t } = useTranslation();
  const priceRows = useMemo(() => buildPriceRows(t), [t]);
  const renderPrice = useCallback(
    (row: CompareRow<ArtificialAnalysisModel>, model: ArtificialAnalysisModel, winner: Winner | null): ReactNode => {
      const value = row.getNumeric?.(model);
      return typeof value === "number" ? (
        <WinnerValue value={formatDollar(value, t)} winner={winner} />
      ) : (
        <span className="text-text-tertiary">{t("notAvailable")}</span>
      );
    },
    [t],
  );

  return (
    <>
      <div className="flex flex-col gap-3">
        <p className="text-sm font-semibold">{t("priceBreakdown")}</p>
        <CompareTable rows={priceRows} models={models} mobileLayout="model-cards" renderValue={renderPrice} />
      </div>
      <Suspense fallback={<PriceChartFallback />}>
        <PriceChart priceRows={priceRows} models={models} />
      </Suspense>
      <CostEstimator models={models} />
    </>
  );
});

function PriceChartFallback() {
  const { t } = useTranslation();
  return <ChartCard title={t("priceComparison")} loading />;
}

export function PriceCompareView() {
  const { t } = useTranslation();
  return (
    <ComparePageLayout backTo={`${MODEL_SOURCES.aa.backTo}&view=pricing`} title={t("priceComparison")}>
      {(models) => <PriceCompareContent models={models} />}
    </ComparePageLayout>
  );
}

// src/client/features/compare/price-compare-view.vue
<script setup lang="ts">
import { computed, h, type VNodeChild } from "vue";
import { useTranslation } from "@/client/i18n";
import type { ArtificialAnalysisModel } from "@/shared/types";
import { formatDollar } from "@/client/utils/format";
import ChartCard from "@/client/components/ui/chart-card.vue";
import CompareTable, { WinnerValue } from "@/client/features/compare/compare-table.vue";
import CostEstimator from "@/client/features/compare/price-compare/estimator.vue";
import { MODEL_SOURCES } from "@/client/config/nav-config";
import { loadableView } from "@/client/router/lazy-view";
import ComparePageLayout from "./compare-layout.vue";
import { buildPriceRows, type CompareRow, type Winner } from "@/client/utils/compare-logic";

const PriceChart = loadableView(() => import("@/client/features/compare/price-compare/price-chart.vue"));

const { t } = useTranslation();

const priceRows = computed(() => buildPriceRows(t));

function renderPrice(
  row: CompareRow<ArtificialAnalysisModel>,
  model: ArtificialAnalysisModel,
  winner: Winner | null,
): VNodeChild {
  const value = row.getNumeric?.(model);
  return typeof value === "number"
    ? h(WinnerValue, { value: formatDollar(value, t), winner })
    : h("span", { class: "text-text-tertiary" }, t("notAvailable"));
}
</script>

<template>
  <ComparePageLayout :back-to="`${MODEL_SOURCES.aa.backTo}&view=pricing`" :title="t('priceComparison')">
    <template #default="{ models }">
      <div class="flex flex-col gap-3">
        <p class="text-sm font-semibold">{{ t("priceBreakdown") }}</p>
        <CompareTable :rows="priceRows" :models="models" :render-value="renderPrice" />
      </div>
      <Suspense>
        <PriceChart :price-rows="priceRows" :models="models" />
        <template #fallback>
          <ChartCard :title="t('priceComparison')" loading />
        </template>
      </Suspense>
      <CostEstimator :models="models" />
    </template>
  </ComparePageLayout>
</template>
