// src/client/components/layout/app-shell.tsx
import { Suspense, useCallback, useEffect, useLayoutEffect, useRef, useState, type ReactNode } from "react";
import { isPopstateNavigation, historyIndex, usePathname, useSearchParams } from "@/client/router";
import { useSettingsStore } from "@/client/stores";
import { useTranslation } from "@/client/providers";
import { DesktopNav, MobileNav } from "./navigation";
import { ErrorBoundary } from "@/client/router/suspense-query";
import { loadableView } from "@/client/router/lazy-view";

const SettingsSheet = loadableView(() => import("./settings-sheet").then((m) => ({ default: m.SettingsSheet })));
const MobileMoreSheet = loadableView(() => import("./mobile-more-sheet").then((m) => ({ default: m.MobileMoreSheet })));

function SheetErrorBoundary({ children }: { children: ReactNode }) {
  const { t } = useTranslation();
  return (
    <ErrorBoundary
      errorTitle={t("errorBoundaryTitle")}
      retryLabel={t("errorBoundaryRetry")}
      offlineMessage={t("offlineRetry")}
    >
      <Suspense fallback={null}>{children}</Suspense>
    </ErrorBoundary>
  );
}

const scrollOffsets = new Map<number, number>();

export function AppShell({ children }: { children: ReactNode }) {
  const [mobileMoreOpen, setMobileMoreOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const themeMode = useSettingsStore((s) => s.themeMode);
  const { t } = useTranslation();
  const mainRef = useRef<HTMLElement>(null);
  const pathname = usePathname();
  const searchParams = useSearchParams();

  const closeSettings = useCallback(() => setSettingsOpen(false), []);
  const closeMore = useCallback(() => setMobileMoreOpen(false), []);
  const openSettings = useCallback(() => {
    setMobileMoreOpen(false);
    setSettingsOpen(true);
  }, []);
  const openMore = useCallback(() => {
    setSettingsOpen(false);
    setMobileMoreOpen(true);
  }, []);

  const [prevPathname, setPrevPathname] = useState(pathname);
  if (prevPathname !== pathname) {
    setPrevPathname(pathname);
    setMobileMoreOpen(false);
    setSettingsOpen(false);
  }

  useLayoutEffect(() => {
    const dark = themeMode === "dark";
    document.documentElement.classList.toggle("dark", dark);
    document.documentElement.style.colorScheme = dark ? "dark" : "light";
    const metas = document.querySelectorAll("meta[name='theme-color']");
    for (const meta of metas) meta.setAttribute("content", dark ? "#1a1a1a" : "#fafbfc");
  }, [themeMode]);

  useEffect(() => {
    const main = mainRef.current;
    if (!main) return;
    const record = () => scrollOffsets.set(historyIndex(), main.scrollTop);
    main.addEventListener("scroll", record, { passive: true });
    return () => main.removeEventListener("scroll", record);
  }, []);

  useLayoutEffect(() => {
    const main = mainRef.current;
    if (!main) return;
    const idx = historyIndex();
    if (isPopstateNavigation()) {
      main.scrollTo({ top: scrollOffsets.get(idx) ?? 0 });
      return;
    }
    for (const key of scrollOffsets.keys()) if (key >= idx) scrollOffsets.delete(key);
    main.scrollTo({ top: 0 });
  }, [pathname, searchParams]);

  return (
    <div className="min-h-screen h-[100dvh] flex flex-col bg-bg-primary overflow-x-hidden pt-[env(safe-area-inset-top,0px)]">
      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-[100] focus:px-4 focus:py-2 focus:bg-bg-primary focus:border focus:border-border focus:text-sm focus:outline-none focus:ring-2 focus:ring-ring"
      >
        {t("skipToContent")}
      </a>
      <DesktopNav onSettingsOpen={openSettings} />
      <main
        ref={mainRef}
        id="main-content"
        tabIndex={-1}
        aria-label={t("mainContent")}
        className="flex-1 min-h-0 overflow-y-auto [scrollbar-gutter:stable] overscroll-contain pb-[calc(4rem+env(safe-area-inset-bottom,0px))] md:pb-4 focus:outline-none"
      >
        {children}
      </main>
      <MobileNav onMoreOpen={openMore} onSettingsOpen={openSettings} />
      {settingsOpen && (
        <SheetErrorBoundary>
          <SettingsSheet open onClose={closeSettings} />
        </SheetErrorBoundary>
      )}
      {mobileMoreOpen && (
        <SheetErrorBoundary>
          <MobileMoreSheet open onClose={closeMore} />
        </SheetErrorBoundary>
      )}
    </div>
  );
}

// src/client/components/layout/app-shell.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from "vue";
import { useRoute } from "vue-router";
import { useSettingsStore } from "@/client/stores";
import { useTranslation } from "@/client/i18n";
import { historyIndex, isPopstateNavigation } from "@/client/router";
import DesktopNav from "@/client/components/layout/desktop-nav.vue";
import MobileNav from "@/client/components/layout/mobile-nav.vue";
import ErrorBoundary from "@/client/components/error-boundary.vue";
import SettingsSheet from "@/client/components/layout/settings-sheet.vue";
import MobileMoreSheet from "@/client/components/layout/mobile-more-sheet.vue";

const scrollOffsets = new Map<number, number>();

const SCROLL_RESTORE_WINDOW_MS = 5_000;

const route = useRoute();
const settings = useSettingsStore();
const { t } = useTranslation();

const openSheet = ref<"settings" | "more" | null>(null);
const mainRef = ref<HTMLElement | null>(null);

let stopRestore: (() => void) | null = null;

function closeSheet(): void {
  openSheet.value = null;
}

function recordScroll(): void {
  const main = mainRef.value;
  if (!main) return;
  scrollOffsets.set(historyIndex(), main.scrollTop);
}

function restoreScroll(): void {
  const main = mainRef.value;
  if (!main) return;
  stopRestore?.();
  stopRestore = null;
  const idx = historyIndex();
  if (!isPopstateNavigation()) {
    for (const key of scrollOffsets.keys()) if (key >= idx) scrollOffsets.delete(key);
    main.scrollTo({ top: 0 });
    return;
  }
  const target = scrollOffsets.get(idx) ?? 0;
  if (target === 0 || main.scrollHeight - main.clientHeight >= target) {
    main.scrollTo({ top: target });
    return;
  }
  const initial = main.scrollTop;
  let cancelled = false;
  const stop = () => {
    cancelled = true;
    clearTimeout(deadline);
    observer.disconnect();
    main.removeEventListener("scroll", onUserScroll);
  };
  const restore = () => {
    if (cancelled || main.scrollHeight - main.clientHeight < target) return;
    stop();
    main.scrollTo({ top: target });
  };
  const onUserScroll = () => {
    if (main.scrollTop !== initial) stop();
  };
  const observer = new MutationObserver(restore);
  const deadline = setTimeout(stop, SCROLL_RESTORE_WINDOW_MS);
  observer.observe(main, { childList: true, subtree: true });
  main.addEventListener("scroll", onUserScroll, { passive: true });
  stopRestore = stop;
}

function applyTheme(): void {
  const dark = settings.themeMode === "dark";
  document.documentElement.classList.toggle("dark", dark);
  document.documentElement.style.colorScheme = dark ? "dark" : "light";
  const metas = document.querySelectorAll("meta[name='theme-color']");
  for (const meta of metas) meta.setAttribute("content", dark ? "#1a1a1a" : "#fafbfc");
}

watch(() => settings.themeMode, applyTheme, { immediate: true, flush: "post" });

watch(
  () => route.fullPath,
  () => {
    openSheet.value = null;
    restoreScroll();
  },
  { flush: "post" },
);

onMounted(() => {
  mainRef.value?.addEventListener("scroll", recordScroll, { passive: true });
  restoreScroll();
});

onUnmounted(() => {
  mainRef.value?.removeEventListener("scroll", recordScroll);
  stopRestore?.();
});
</script>

<template>
  <div class="min-h-screen h-[100dvh] flex flex-col bg-bg-primary overflow-x-hidden pt-[env(safe-area-inset-top,0px)]">
    <a
      href="#main-content"
      class="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-[100] focus:px-4 focus:py-2 focus:bg-bg-primary focus:border focus:border-border focus:text-sm focus:outline-none focus:ring-2 focus:ring-ring"
    >
      {{ t("skipToContent") }}
    </a>
    <DesktopNav @settings-open="openSheet = 'settings'" />
    <main
      ref="mainRef"
      id="main-content"
      tabindex="-1"
      :aria-label="t('mainContent')"
      class="flex-1 min-h-0 overflow-y-auto [scrollbar-gutter:stable] overscroll-contain pb-[calc(4rem+env(safe-area-inset-bottom,0px))] md:pb-4 focus:outline-none"
    >
      <slot />
    </main>
    <MobileNav @more-open="openSheet = 'more'" @settings-open="openSheet = 'settings'" />
    <ErrorBoundary v-if="openSheet === 'settings'" key="settings">
      <SettingsSheet :open="true" @close="closeSheet" />
    </ErrorBoundary>
    <ErrorBoundary v-if="openSheet === 'more'" key="more">
      <MobileMoreSheet :open="true" @close="closeSheet" />
    </ErrorBoundary>
  </div>
</template>
