// src/client/components/shared/BackButton.tsx
import { useNavigate } from "react-router";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/client/components/ui";
import { useTranslation } from "@/client/providers";
import type { TranslationKey } from "@/shared/i18n";

/**
 * Navigates to a target route, forwarding optional router state so the
 * destination page can restore context (e.g. a previously selected model).
 */
export function BackButton({ labelKey, to, state }: { labelKey: TranslationKey; to: string; state?: unknown }) {
  const navigate = useNavigate();
  const { t } = useTranslation();
  return (
    <Button size="sm" variant="outline" onClick={() => navigate(to, { state })} className="self-start">
      <ArrowLeft className="size-4" /> {t(labelKey)}
    </Button>
  );
}

// src/client/components/layout/back-button.vue
<script setup lang="ts">
import { ArrowLeft } from "@lucide/vue";
import type { TranslationKey } from "@/shared/i18n";
import { useTranslation } from "@/client/i18n";
import { canGoBack, historyFrom } from "@/client/router";
import { useRouter } from "vue-router";
import Button from "@/client/components/ui/button.vue";

const props = defineProps<{ labelKey: TranslationKey; to: string }>();

const router = useRouter();
const { t } = useTranslation();

function goBack(): void {
  if (canGoBack()) router.back();
  else void router.replace(props.to);
}
</script>

<template>
  <Button size="sm" variant="outline" class="self-start" @click="goBack">
    <ArrowLeft class="size-4" />
    {{ historyFrom() == null || historyFrom() === to ? t(labelKey) : t("back") }}
  </Button>
</template>
