// src/client/components/layout/mobile-nav.vue
<script setup lang="ts">
import { computed } from "vue";
import { MoreHorizontal, Settings } from "@lucide/vue";
import { useTranslation } from "@/client/i18n";
import { usePathname } from "@/client/router";
import { isNavActive, useNavigation, usePrefetch } from "@/client/components/layout/navigation";
import SafeLink from "@/client/components/safe-link.vue";

const emit = defineEmits<{ moreOpen: []; settingsOpen: [] }>();

const pathname = usePathname();
const { t } = useTranslation();
const { mobilePrimary, mobileMore } = useNavigation();
const { touch } = usePrefetch();

const BAR_BUTTON =
  "flex-1 flex flex-col items-center justify-center gap-1 text-center text-xs font-medium transition-colors duration-fast focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring/30 min-h-16 py-2";

const barItemClass = (active: boolean) => `${BAR_BUTTON} relative ${active ? "text-accent" : "text-text-secondary"}`;

const isMoreActive = computed(() => mobileMore.value.some((item) => isNavActive(pathname.value, item)));
</script>

<template>
  <nav
    class="md:hidden fixed left-0 right-0 bottom-0 z-30 flex h-16 items-stretch border-t border-border bg-bg-primary pb-[env(safe-area-inset-bottom,0px)]"
    :aria-label="t('navPrimaryMobile')"
  >
    <SafeLink
      v-for="item in mobilePrimary"
      :key="item.path"
      :href="item.path"
      :aria-label="item.label"
      :aria-current="isNavActive(pathname, item) ? 'page' : undefined"
      :class="barItemClass(isNavActive(pathname, item))"
      @touchstart="touch(item.path)"
    >
      <span
        v-if="isNavActive(pathname, item)"
        class="absolute top-0 left-1/4 right-1/4 h-0.5 bg-accent"
        aria-hidden="true"
      />
      <component :is="item.icon" :size="18" />
      <span>{{ item.label }}</span>
    </SafeLink>
    <button type="button" :aria-label="t('more')" :class="barItemClass(isMoreActive)" @click="emit('moreOpen')">
      <span v-if="isMoreActive" class="absolute top-0 left-1/4 right-1/4 h-0.5 bg-accent" aria-hidden="true" />
      <MoreHorizontal :size="18" />
      <span>{{ t("more") }}</span>
    </button>
    <button type="button" :aria-label="t('settings')" :class="barItemClass(false)" @click="emit('settingsOpen')">
      <Settings :size="18" />
      <span>{{ t("settings") }}</span>
    </button>
  </nav>
</template>

// src/client/components/layout/MobileNav.tsx
import { NavLink, useLocation } from "react-router";
import { MoreHorizontal, Settings } from "lucide-react";
import { useTranslation } from "@/client/providers";
import { useNavigation, isNavActive } from "./navigation";

interface MobileNavProps {
  onMoreOpen: () => void;
  onSettingsOpen: () => void;
}

/** Fixed bottom navigation bar for mobile; primary items plus a "More" button. */
export function MobileNav({ onMoreOpen, onSettingsOpen }: MobileNavProps) {
  const { pathname } = useLocation();
  const { t } = useTranslation();
  const { mobilePrimary, mobileMore } = useNavigation();

  // Highlight "More" when the current route belongs to a secondary (collapsed) nav item.
  const isMoreActive = mobileMore.some((n) => isNavActive(pathname, n));

  return (
    <nav
      className="md:hidden fixed left-1/2 -translate-x-1/2 bottom-[calc(env(safe-area-inset-bottom,0px)+0.75rem)] z-30 flex h-14 items-center rounded-full border border-border bg-nav-bg backdrop-blur-lg shadow-lg"
      aria-label={t("navPrimaryMobile")}
    >
      {mobilePrimary.map((item) => {
        const active = isNavActive(pathname, item);
        return (
          <NavLink
            key={item.path}
            to={item.path}
            aria-label={item.label}
            aria-current={active ? "page" : undefined}
            className={`w-20 flex flex-col items-center justify-center gap-0.5 text-[11px] font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/40 rounded-full ${active ? "text-accent" : "text-text-secondary"}`}
          >
            {item.icon}
            <span>{item.label}</span>
          </NavLink>
        );
      })}
      <button
        type="button"
        onClick={onMoreOpen}
        aria-label={t("more")}
        className={`w-20 flex flex-col items-center justify-center gap-0.5 text-[11px] font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/40 rounded-full ${isMoreActive ? "text-accent" : "text-text-secondary"}`}
      >
        <MoreHorizontal size={18} />
        <span>{t("more")}</span>
      </button>
      <button
        type="button"
        onClick={onSettingsOpen}
        aria-label={t("settings")}
        className="w-20 flex flex-col items-center justify-center gap-0.5 text-[11px] font-medium transition-colors text-text-secondary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/40 rounded-full"
      >
        <Settings size={18} />
        <span>{t("settings")}</span>
      </button>
    </nav>
  );
}
