// src/client/components/layout/MobileMoreSheet.tsx
import { NavLink, useLocation } from "react-router";
import { useNavigation, isNavActive } from "./navigation";
import { useTranslation } from "@/client/providers";
import { Sheet } from "@/client/components/ui";
import type { NavItem } from "./navigation";

interface MobileMoreSheetProps {
  open: boolean;
  onClose: () => void;
}

const tileClass = (active: boolean) =>
  `flex flex-col items-center gap-1.5 w-20 py-3 rounded-xl text-xs font-medium transition-colors ${
    active ? "bg-selected text-accent" : "text-text-secondary hover:bg-hover"
  }`;

/** Compact floating "More" menu on mobile: icon-tile grid hovering above the bottom nav. */
export function MobileMoreSheet({ open, onClose }: MobileMoreSheetProps) {
  const { pathname } = useLocation();
  const { mobileMore } = useNavigation();
  const { t } = useTranslation();

  return (
    <Sheet open={open} onClose={onClose} className="w-auto mb-24 rounded-2xl p-2" ariaLabel={t("navMore")}>
      <nav className="flex gap-1" aria-label={t("navSecondary")}>
        {mobileMore.map((item) => {
          const active = isNavActive(pathname, item);
          return <NavTile key={item.path} item={item} active={active} onClose={onClose} />;
        })}
      </nav>
    </Sheet>
  );
}

function NavTile({ item, active, onClose }: { item: NavItem; active: boolean; onClose: () => void }) {
  return (
    <NavLink to={item.path} onClick={onClose} aria-current={active ? "page" : undefined} className={tileClass(active)}>
      <span className="[&>svg]:size-[22px]">{item.icon}</span>
      <span>{item.label}</span>
    </NavLink>
  );
}

// src/client/components/layout/mobile-more-sheet.vue
<script setup lang="ts">
import { ChevronRight } from "@lucide/vue";
import { useTranslation } from "@/client/i18n";
import { usePathname } from "@/client/router";
import { isNavActive, useNavigation, usePrefetch } from "@/client/components/layout/navigation";
import Sheet from "@/client/components/ui/sheet.vue";
import SheetBody from "@/client/components/ui/sheet-body.vue";
import SheetHeader from "@/client/components/ui/sheet-header.vue";
import SafeLink from "@/client/components/safe-link.vue";

defineProps<{ open: boolean }>();
const emit = defineEmits<{ close: [] }>();

const pathname = usePathname();
const { mobileMore } = useNavigation();
const { t } = useTranslation();
const prefetch = usePrefetch();
</script>

<template>
  <Sheet :open="open" :aria-label="t('navMore')" @close="emit('close')">
    <SheetBody>
      <SheetHeader :title="t('more')" @close="emit('close')" />

      <nav class="divide-y divide-border" :aria-label="t('navSecondary')">
        <SafeLink
          v-for="item in mobileMore"
          :key="item.path"
          :href="item.path"
          :aria-current="isNavActive(pathname, item) ? 'page' : undefined"
          :class="[
            'flex items-center justify-between gap-3 px-4 py-3 transition-colors duration-fast focus-visible:outline-none focus-visible:bg-hover',
            isNavActive(pathname, item) ? 'text-accent' : 'text-text-primary hoverable:hover:bg-hover',
          ]"
          @click="emit('close')"
          @touchstart="prefetch.touch(item.path)"
          @mouseenter="prefetch.hover(item.path)"
          @mouseleave="prefetch.cancel"
          @focus="prefetch.hover(item.path)"
          @blur="prefetch.cancel"
        >
          <span class="flex items-center gap-2 min-w-0">
            <span :class="isNavActive(pathname, item) ? 'text-accent shrink-0' : 'text-text-secondary shrink-0'">
              <component :is="item.icon" :size="18" />
            </span>
            <span class="text-sm">{{ item.label }}</span>
          </span>
          <ChevronRight :size="16" class="text-text-tertiary shrink-0" aria-hidden="true" />
        </SafeLink>
      </nav>
    </SheetBody>
  </Sheet>
</template>
