// src/client/components/layout/settings-sheet.vue
<script setup lang="ts">
import { computed } from "vue";
import { Languages, SunMoon } from "@lucide/vue";
import { useTranslation } from "@/client/i18n";
import { useSettingsStore } from "@/client/stores";
import Sheet from "@/client/components/ui/sheet.vue";
import SheetBody from "@/client/components/ui/sheet-body.vue";
import SheetHeader from "@/client/components/ui/sheet-header.vue";
import SettingsSegmented from "@/client/components/layout/settings-segmented.vue";

defineProps<{ open: boolean }>();
const emit = defineEmits<{ close: [] }>();

const { t, lang, setLang } = useTranslation();
const settings = useSettingsStore();

const languageOptions = computed(() => [
  { value: "zh", label: t("langZh") },
  { value: "en", label: t("langEn") },
]);

const themeOptions = computed(() => [
  { value: "light", label: t("themeLight") },
  { value: "dark", label: t("themeDark") },
]);
</script>

<template>
  <Sheet :open="open" :aria-label="t('settings')" @close="emit('close')">
    <SheetBody>
      <SheetHeader :title="t('settings')" @close="emit('close')" />

      <div class="divide-y divide-border">
        <div class="flex items-center justify-between gap-3 px-4 py-3">
          <div class="flex items-center gap-2 min-w-0">
            <span class="text-text-secondary shrink-0"><Languages :size="16" /></span>
            <p class="text-sm">{{ t("language") }}</p>
          </div>
          <SettingsSegmented
            :label="t('language')"
            id-prefix="language"
            :value="lang"
            :options="languageOptions"
            @change="(value) => (value === 'zh' || value === 'en') && setLang(value)"
          />
        </div>
        <div class="flex items-center justify-between gap-3 px-4 py-3">
          <div class="flex items-center gap-2 min-w-0">
            <span class="text-text-secondary shrink-0"><SunMoon :size="16" /></span>
            <p class="text-sm">{{ t("themeToggle") }}</p>
          </div>
          <SettingsSegmented
            :label="t('themeToggle')"
            id-prefix="theme"
            :value="settings.themeMode"
            :options="themeOptions"
            @change="(value) => (value === 'light' || value === 'dark') && settings.setThemeMode(value)"
          />
        </div>
      </div>
    </SheetBody>
  </Sheet>
</template>

// src/client/components/layout/settings-sheet.tsx
import { memo, type ReactNode } from "react";
import { Languages, SunMoon } from "lucide-react";
import { useTranslation } from "@/client/providers";
import { useSettingsStore } from "@/client/stores";
import { SegmentedGroup } from "@/client/components/ui/grids";
import { TabButton, nextIndexForKey } from "@/client/components/ui/tabs";
import { Sheet, SheetBody, SheetHeader } from "@/client/components/ui/sheet";

const Segmented = memo(function Segmented({
  value,
  onChange,
  options,
  label,
}: {
  value: string;
  onChange: (v: string) => void;
  options: { value: string; label: ReactNode }[];
  label?: string;
}) {
  const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    const next = nextIndexForKey(
      e.key,
      options.findIndex((o) => o.value === value),
      options.length,
    );
    if (next == null) return;
    e.preventDefault();
    const target = options[next];
    if (target) {
      onChange(target.value);
      document.getElementById(`setting-${label}-${target.value}`)?.focus();
    }
  };

  return (
    <SegmentedGroup role="radiogroup" aria-label={label} onClick={(e) => e.stopPropagation()} onKeyDown={handleKeyDown}>
      {options.map((opt) => (
        <TabButton
          key={opt.value}
          role="radio"
          size="sm"
          active={value === opt.value}
          onClick={() => onChange(opt.value)}
          id={`setting-${label}-${opt.value}`}
        >
          {opt.label}
        </TabButton>
      ))}
    </SegmentedGroup>
  );
});

const SettingRow = memo(function SettingRow({
  icon,
  label,
  children,
}: {
  icon: ReactNode;
  label: string;
  children: ReactNode;
}) {
  return (
    <div className="flex items-center justify-between gap-3 px-4 py-3">
      <div className="flex items-center gap-2 min-w-0">
        <span className="text-text-secondary shrink-0">{icon}</span>
        <p className="text-sm">{label}</p>
      </div>
      {children}
    </div>
  );
});

export function SettingsSheet({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { t, lang, setLang } = useTranslation();
  const themeMode = useSettingsStore((s) => s.themeMode);
  const setThemeMode = useSettingsStore((s) => s.setThemeMode);

  return (
    <Sheet open={open} onClose={onClose} ariaLabel={t("settings")}>
      <SheetBody>
        <SheetHeader title={t("settings")} onClose={onClose} />

        <div className="divide-y divide-border">
          <SettingRow icon={<Languages size={16} />} label={t("language")}>
            <Segmented
              label={t("language")}
              value={lang}
              onChange={(v) => {
                if (v === "zh" || v === "en") setLang(v);
              }}
              options={[
                { value: "zh", label: "中文" },
                { value: "en", label: "EN" },
              ]}
            />
          </SettingRow>
          <SettingRow icon={<SunMoon size={16} />} label={t("themeToggle")}>
            <Segmented
              label={t("themeToggle")}
              value={themeMode}
              onChange={(v) => {
                if (v === "light" || v === "dark") setThemeMode(v);
              }}
              options={[
                { value: "light", label: t("themeLight") },
                { value: "dark", label: t("themeDark") },
              ]}
            />
          </SettingRow>
        </div>
      </SheetBody>
    </Sheet>
  );
}
